insert into BRAND (id, name) values (1, 'Aplicare Povidone-iodine Scrub');
insert into BRAND (id, name) values (2, 'Felodipine');
insert into BRAND (id, name) values (3, 'LODOSYN');
insert into BRAND (id, name) values (4, 'equaline naproxen sodium');
insert into BRAND (id, name) values (5, 'Perfecting Liquid Foundation Alabaster');
insert into BRAND (id, name) values (6, 'Western Ragweed');
insert into BRAND (id, name) values (7, 'Nighttime Sleep Aid');
insert into BRAND (id, name) values (8, 'Dextrose and Sodium Chloride');
insert into BRAND (id, name) values (9, 'Calm Drops');
insert into BRAND (id, name) values (10, 'Cetirizine Hydrochloride and Pseudoephedrine Hydrochloride');
insert into BRAND (id, name) values (11, 'Vinorelbine');
insert into BRAND (id, name) values (12, 'Fabior');
insert into BRAND (id, name) values (13, 'Ribavirin');
insert into BRAND (id, name) values (14, 'Cystografin Dilute');
insert into BRAND (id, name) values (15, 'Mirtazapine');
insert into BRAND (id, name) values (16, 'DRAXIMAGE MAA');
insert into BRAND (id, name) values (17, 'APIS MELLIFICA');
insert into BRAND (id, name) values (18, 'Valacyclovir');
insert into BRAND (id, name) values (19, 'Otoflam');
insert into BRAND (id, name) values (20, 'Dandruff');
insert into BRAND (id, name) values (21, 'Simple');
insert into BRAND (id, name) values (22, 'Full Care Three Povidone Iodine Swabsticks');
insert into BRAND (id, name) values (23, 'Opahl');
insert into BRAND (id, name) values (24, 'CULTIVATED CORN POLLEN');
insert into BRAND (id, name) values (25, 'Turnip');
insert into BRAND (id, name) values (26, 'Wheat Stem Rust');
insert into BRAND (id, name) values (27, 'Propranolol Hydrochloride');
insert into BRAND (id, name) values (28, 'supernatural airbrushed canvas broad spectrum spf 15 sunscreen');
insert into BRAND (id, name) values (29, 'Bronco Pulmonar Syrup');
insert into BRAND (id, name) values (30, 'Pain Relief');
insert into BRAND (id, name) values (31, 'Tretin-X');
insert into BRAND (id, name) values (32, 'Dollar General');
insert into BRAND (id, name) values (33, 'HYDROCODONE BITARTRATE AND ACETAMINOPHEN');
insert into BRAND (id, name) values (34, 'PhysiciansCare Ophthalmic Solution Eyewash');
insert into BRAND (id, name) values (35, 'sunmark antacid');
insert into BRAND (id, name) values (36, 'Bisoprolol Fumarate and Hydrochlorothiazide');
insert into BRAND (id, name) values (37, 'SENSAI CELLULAR PERFORMANCE POWDER FOUNDATION');
insert into BRAND (id, name) values (38, 'Sugar Maple');
insert into BRAND (id, name) values (39, 'Quinidine Gluconate');
insert into BRAND (id, name) values (40, 'Mark 3');
insert into BRAND (id, name) values (41, 'Gabapentin');
insert into BRAND (id, name) values (42, 'Helium');
insert into BRAND (id, name) values (43, 'Skin Protectant');
insert into BRAND (id, name) values (44, 'Glipizide and Metformin Hydrochloride');
insert into BRAND (id, name) values (45, 'Sensodyne Pronamel');
insert into BRAND (id, name) values (46, 'Jantoven');
insert into BRAND (id, name) values (47, 'OP Protective Spray Gel 8');
insert into BRAND (id, name) values (48, 'Roota Re V for women');
insert into BRAND (id, name) values (49, 'Proventil HFA');
insert into BRAND (id, name) values (50, 'CAPTOPRIL');
insert into BRAND (id, name) values (51, 'Muscle and Joint');
insert into BRAND (id, name) values (52, 'Etodolac');
insert into BRAND (id, name) values (53, 'ESIKA');
insert into BRAND (id, name) values (54, 'IMITREX');
insert into BRAND (id, name) values (55, 'Famciclovir');
insert into BRAND (id, name) values (56, 'Rimmel London');
insert into BRAND (id, name) values (57, 'LEADER DRY EYE RELIEF');
insert into BRAND (id, name) values (58, 'Alba Mineral Terra Tint SPF15 Garnet');
insert into BRAND (id, name) values (59, 'Pleo Ut S');
insert into BRAND (id, name) values (60, 'Idamycin PFS');
insert into BRAND (id, name) values (61, 'Denti-Care Denti-Foam');
insert into BRAND (id, name) values (62, 'Povidone-Iodine');
insert into BRAND (id, name) values (63, 'Trazodone Hydrochloride');
insert into BRAND (id, name) values (64, 'Phendimetrazine Tartrate');
insert into BRAND (id, name) values (65, 'Alendronate Sodium');
insert into BRAND (id, name) values (66, 'Trazodone Hydrochloride');
insert into BRAND (id, name) values (67, 'DiorSkin Forever Wear Extending Invisible Retouch SPF 8 - 001');
insert into BRAND (id, name) values (68, 'Sertraline Hydrochloride');
insert into BRAND (id, name) values (69, 'DURAGESIC');
insert into BRAND (id, name) values (70, 'Jason Pure Natural Sun Mineral Natural Sunscreen Broad Spectrum SPF30');
insert into BRAND (id, name) values (71, 'em michelle phan the everything tinted makeup cc');
insert into BRAND (id, name) values (72, 'Simvastatin');
insert into BRAND (id, name) values (73, 'Medicated Chest');
insert into BRAND (id, name) values (74, 'HYDREA');
insert into BRAND (id, name) values (75, 'Sonata');
insert into BRAND (id, name) values (76, 'Feather Mixture');
insert into BRAND (id, name) values (77, 'Headache Relief');
insert into BRAND (id, name) values (78, 'CD DiorSkin Forever Compact Flawless Perfection Fusion Wear Makeup SPF 25 - 040');
insert into BRAND (id, name) values (79, 'Telmisartan and Hydrochlorothiazide');
insert into BRAND (id, name) values (80, 'Clonidine Hydrochloride');
insert into BRAND (id, name) values (81, 'Cold Sores and Herpes');
insert into BRAND (id, name) values (82, 'Divalproex Sodium');
insert into BRAND (id, name) values (83, 'Fenofibrate');
insert into BRAND (id, name) values (84, 'Pep-Back');
insert into BRAND (id, name) values (85, 'levocetirizine dihydrochloride');
insert into BRAND (id, name) values (86, 'Budeprion');
insert into BRAND (id, name) values (87, 'Bupropion Hydrochloride');
insert into BRAND (id, name) values (88, 'Sally Hansen Microwavable Eybrow, Face and Lip Wax Kit');
insert into BRAND (id, name) values (89, 'AZITHROMYCIN');
insert into BRAND (id, name) values (90, 'urocit-k');
insert into BRAND (id, name) values (91, 'risedronate sodium');
insert into BRAND (id, name) values (92, 'Homeopathic Acne Formula');
insert into BRAND (id, name) values (93, 'Docetaxel');
insert into BRAND (id, name) values (94, 'Glipizide');
insert into BRAND (id, name) values (95, 'Neut Sodium Bicarbonate');
insert into BRAND (id, name) values (96, 'Azathioprine');
insert into BRAND (id, name) values (97, 'Ifosfamide');
insert into BRAND (id, name) values (98, 'Yaz');
insert into BRAND (id, name) values (99, 'Amlodipine besylate and Atorvastatin calcium');
insert into BRAND (id, name) values (100, 'Relaxation Complex');
insert into BRAND (id, name) values (101, 'Mucor');
insert into BRAND (id, name) values (102, 'pain relief');
insert into BRAND (id, name) values (103, 'MYCAMINE');
insert into BRAND (id, name) values (104, 'MILLIPRED');
insert into BRAND (id, name) values (105, 'Blistex');
insert into BRAND (id, name) values (106, 'Oat Grain');
insert into BRAND (id, name) values (107, 'Select Brand Antacid Assorted Berries');
insert into BRAND (id, name) values (108, 'Xerese');
insert into BRAND (id, name) values (109, 'Erythromycin');
insert into BRAND (id, name) values (110, 'LACURA');
insert into BRAND (id, name) values (111, 'PENICILLIN G PROCAINE');
insert into BRAND (id, name) values (112, 'CEFTRIAXONE');
insert into BRAND (id, name) values (113, 'ACT Restoring Anticavity Fluoride Cool Mint');
insert into BRAND (id, name) values (114, 'Capsicum Chamomilla');
insert into BRAND (id, name) values (115, 'Dutoprol');
insert into BRAND (id, name) values (116, 'CHAMOMILLA');
insert into BRAND (id, name) values (117, 'night time');
insert into BRAND (id, name) values (118, 'acid relief');
insert into BRAND (id, name) values (119, 'Colistimethate');
insert into BRAND (id, name) values (120, 'OPANA');
insert into BRAND (id, name) values (121, 'Cepacol');
insert into BRAND (id, name) values (122, 'DOXEPIN HYDROCHLORIDE');
insert into BRAND (id, name) values (123, 'ESTRADIOL');
insert into BRAND (id, name) values (124, 'FLECTOR');
insert into BRAND (id, name) values (125, 'Vineyard Grape Antibacterial Hand Wash');
insert into BRAND (id, name) values (126, 'Ultracare For Hands');
insert into BRAND (id, name) values (127, 'DIPHENHYDRAMINE HYDROCHLORIDE');
insert into BRAND (id, name) values (128, 'Duloxetine');
insert into BRAND (id, name) values (129, 'Nuvel Hand Sanitizer');
insert into BRAND (id, name) values (130, 'CYBERWHITE HD UV PROTECTOR BROAD SPECTRUM SPF 50');
insert into BRAND (id, name) values (131, 'Lidocaine and Prilocaine');
insert into BRAND (id, name) values (132, 'Cover Fx BB Gel Mattifying Anti-Blemish N Light');
insert into BRAND (id, name) values (133, 'ibuprofen');
insert into BRAND (id, name) values (134, 'Super Aqua Night');
insert into BRAND (id, name) values (135, 'Tretinoin');
insert into BRAND (id, name) values (136, 'Dermablend Quick Fix Concealer');
insert into BRAND (id, name) values (137, 'Paroxetine Hydrochloride');
insert into BRAND (id, name) values (138, 'Bismutina');
insert into BRAND (id, name) values (139, 'Vectibix');
insert into BRAND (id, name) values (140, 'Zaleplon');
insert into BRAND (id, name) values (141, 'Pain Reliever PM');
insert into BRAND (id, name) values (142, 'Peptic Relief');
insert into BRAND (id, name) values (143, 'Kroger Oil Free Sunscreen');
insert into BRAND (id, name) values (144, 'ARTHROTEC');
insert into BRAND (id, name) values (145, 'Psoriasin');
insert into BRAND (id, name) values (146, 'Smart Sense Adult Tussin DM');
insert into BRAND (id, name) values (147, 'GOLD CAVIAR COLLAGEN SERUM');
insert into BRAND (id, name) values (148, 'Opahl');
insert into BRAND (id, name) values (149, 'Eve Lom Radiance Lift Foundation SPF 15');
insert into BRAND (id, name) values (150, 'Reeva Antibacterial Green Apple');
insert into BRAND (id, name) values (151, 'Hydrocodone Bitartrate and Acetaminophen');
insert into BRAND (id, name) values (152, 'Aspirin Chewable');
insert into BRAND (id, name) values (153, 'CHILDRENS ALLERGY');
insert into BRAND (id, name) values (154, 'AXIRON');
insert into BRAND (id, name) values (155, 'Rheumatoid Arthritis Nosode');
insert into BRAND (id, name) values (156, 'Diflucan');
insert into BRAND (id, name) values (157, 'Good Care Povidone Iodine');
insert into BRAND (id, name) values (158, 'sinus relief');
insert into BRAND (id, name) values (159, 'CellCept');
insert into BRAND (id, name) values (160, 'Garnier Fructis Antidandruff');
insert into BRAND (id, name) values (161, 'Honey Almond Antibacterial Foaming Hand Wash');
insert into BRAND (id, name) values (162, 'Propranolol Hydrochloride');
insert into BRAND (id, name) values (163, 'Bald Cypress');
insert into BRAND (id, name) values (164, 'Ciprofloxacin');
insert into BRAND (id, name) values (165, 'Cefoxitin');
insert into BRAND (id, name) values (166, 'VANCOMYCIN HYDROCHLORIDE');
insert into BRAND (id, name) values (167, 'NATRUM SULPHURICUM');
insert into BRAND (id, name) values (168, 'Clozapine');
insert into BRAND (id, name) values (169, 'FAMOTIDINE');
insert into BRAND (id, name) values (170, 'Propranolol Hydrochloride');
insert into BRAND (id, name) values (171, 'Pantoprazole Sodium');
insert into BRAND (id, name) values (172, 'Darby');
insert into BRAND (id, name) values (173, 'Azathioprine');
insert into BRAND (id, name) values (174, 'Norpramin');
insert into BRAND (id, name) values (175, 'Medi-First First Aid Eye Wash');
insert into BRAND (id, name) values (176, 'Wheat Bunt');
insert into BRAND (id, name) values (177, 'HAND SANITIZER');
insert into BRAND (id, name) values (178, 'Quetiapine Fumarate');
insert into BRAND (id, name) values (179, 'Soothe');
insert into BRAND (id, name) values (180, 'Glyburide');
insert into BRAND (id, name) values (181, 'Alcohol Prep Pad');
insert into BRAND (id, name) values (182, 'CAPTOPRIL');
insert into BRAND (id, name) values (183, 'Zapotol Bacitracin');
insert into BRAND (id, name) values (184, 'Leader ibuprofen');
insert into BRAND (id, name) values (185, 'MEDI-FIRST Non-Aspirin');
insert into BRAND (id, name) values (186, 'Quetiapine fumarate');
insert into BRAND (id, name) values (187, 'Hydrogen Peroxide');
insert into BRAND (id, name) values (188, 'CLARINS UV PLUS HP Broad Spectrum SPF 40 Sunscreen Multi-Protection Tint DEEP');
insert into BRAND (id, name) values (189, 'MAJOR DOK Docusate Sodium');
insert into BRAND (id, name) values (190, 'Equaline 12 Hour Decongestant');
insert into BRAND (id, name) values (191, 'Zaleplon');
insert into BRAND (id, name) values (192, 'BLEMISH');
insert into BRAND (id, name) values (193, 'Lemon Verbena Antibacterial Hand Wash');
insert into BRAND (id, name) values (194, 'VFEND');
insert into BRAND (id, name) values (195, 'SALIX NIGRA POLLEN');
insert into BRAND (id, name) values (196, 'LBEL Couleur luxe rouge irresistible maximum hydration SPF 17');
insert into BRAND (id, name) values (197, 'Aspercreme Heat');
insert into BRAND (id, name) values (198, 'Ifosfamide');
insert into BRAND (id, name) values (199, 'Amoxicillin and Clavulanate Potassium');
insert into BRAND (id, name) values (200, 'Cattle Epithelium');
insert into BRAND (id, name) values (201, 'Dextrose');
insert into BRAND (id, name) values (202, 'losartan potassium');
insert into BRAND (id, name) values (203, 'Depo-Medrol');
insert into BRAND (id, name) values (204, 'Iodine Bush Pollen');
insert into BRAND (id, name) values (205, 'Rhubarb');
insert into BRAND (id, name) values (206, 'Primidone');
insert into BRAND (id, name) values (207, 'Tramadol Hydrochloride');
insert into BRAND (id, name) values (208, 'Pramoxine hydrochloride');
insert into BRAND (id, name) values (209, 'Dry Idea Advanced Dry-Powder Fresh');
insert into BRAND (id, name) values (210, 'Naproxen');
insert into BRAND (id, name) values (211, 'Pleo Lat');
insert into BRAND (id, name) values (212, 'CENTER-AL - BROMUS INERMIS POLLEN');
insert into BRAND (id, name) values (213, 'SANCTURA');
insert into BRAND (id, name) values (214, 'TAXODIUM DISTICHUM POLLEN');
insert into BRAND (id, name) values (215, 'Alodox');
insert into BRAND (id, name) values (216, 'Furosemide');
insert into BRAND (id, name) values (217, 'topcare miconazole 3');
insert into BRAND (id, name) values (218, 'Nitroglycerin Transdermal Delivery System');
insert into BRAND (id, name) values (219, 'loperamide hydrochloride');
insert into BRAND (id, name) values (220, 'Neomycin and Polymyxin B Sulfates and Dexamethasone');
insert into BRAND (id, name) values (221, 'Antibactierial Hand Sanitizer');
insert into BRAND (id, name) values (222, 'Edluar');
insert into BRAND (id, name) values (223, 'Methadone Hydrochloride');
insert into BRAND (id, name) values (224, 'Antibacterial');
insert into BRAND (id, name) values (225, 'Amazonian Colored Clay Foundation Broad Spectrum SPF 15 Sunscreen');
insert into BRAND (id, name) values (226, 'CTx3 Rinse');
insert into BRAND (id, name) values (227, 'Baby Orajel Naturals');
insert into BRAND (id, name) values (228, 'Island Blossom Antibacterial Foaming Hand Wash');
insert into BRAND (id, name) values (229, 'Saltbush');
insert into BRAND (id, name) values (230, 'Tindamax');
insert into BRAND (id, name) values (231, 'All-Natural Pen Spray');
insert into BRAND (id, name) values (232, 'Imipramine Hydrochloride');
insert into BRAND (id, name) values (233, 'VERELAN');
insert into BRAND (id, name) values (234, 'HYDROMORPHONE HYDROCHLORIDE');
insert into BRAND (id, name) values (235, 'ORCHID BY H E B');
insert into BRAND (id, name) values (236, 'Banana Boat Ultra Defense SPF 30 Canada');
insert into BRAND (id, name) values (237, 'Dollar General');
insert into BRAND (id, name) values (238, 'Guilt');
insert into BRAND (id, name) values (239, 'Happy Happy');
insert into BRAND (id, name) values (240, 'mixed vespid hymenoptera venom multidose');
insert into BRAND (id, name) values (241, 'Eucalyptus');
insert into BRAND (id, name) values (242, 'Omeprazole');
insert into BRAND (id, name) values (243, 'Castor Oil');
insert into BRAND (id, name) values (244, 'Nitrofurantoin (macrocrystals)');
insert into BRAND (id, name) values (245, 'Hydroxyzine Pamoate');
insert into BRAND (id, name) values (246, 'clear days ahead');
insert into BRAND (id, name) values (247, 'Sunmark childrens pain and fever');
insert into BRAND (id, name) values (248, 'West Wheat Grass');
insert into BRAND (id, name) values (249, 'POPPY SEED');
insert into BRAND (id, name) values (250, 'Nitrogen');
insert into BRAND (id, name) values (251, 'Penicilium chrysogenum');
insert into BRAND (id, name) values (252, 'Suphedrine');
insert into BRAND (id, name) values (253, 'Nifedipine');
insert into BRAND (id, name) values (254, 'Ramipril');
insert into BRAND (id, name) values (255, 'Deferoxamine Mesylate');
insert into BRAND (id, name) values (256, 'Isuprel');
insert into BRAND (id, name) values (257, 'Gas Relief');
insert into BRAND (id, name) values (258, 'Good Sense Childrens Cold and Cough');
insert into BRAND (id, name) values (259, 'Tolnafate');
insert into BRAND (id, name) values (260, 'Amoxicillin');
insert into BRAND (id, name) values (261, 'Salsalate');
insert into BRAND (id, name) values (262, 'Midazolam Hydrochloride');
insert into BRAND (id, name) values (263, 'Lamotrigine');
insert into BRAND (id, name) values (264, 'TRANZGEL');
insert into BRAND (id, name) values (265, 'Medi-First');
insert into BRAND (id, name) values (266, 'SEROQUEL');
insert into BRAND (id, name) values (267, 'Doxazosin');
insert into BRAND (id, name) values (268, 'Montelukast Sodium');
insert into BRAND (id, name) values (269, 'Neutrogena');
insert into BRAND (id, name) values (270, 'WRINKLESS PLUS');
insert into BRAND (id, name) values (271, 'PreferaOB One');
insert into BRAND (id, name) values (272, 'Nite Aid Sleep Aid');
insert into BRAND (id, name) values (273, 'medroxyprogesterone acetate');
insert into BRAND (id, name) values (274, 'Promethazine Hydrochloride');
insert into BRAND (id, name) values (275, 'Ammonium Lactate');
insert into BRAND (id, name) values (276, 'Tri-Vit with Fluoride Drops');
insert into BRAND (id, name) values (277, 'Solu-Medrol');
insert into BRAND (id, name) values (278, 'Aire-Master Sanitizer Gel vit e/a');
insert into BRAND (id, name) values (279, 'Butalbital, Acetaminophen and Caffeine');
insert into BRAND (id, name) values (280, 'Verapamil Hydrochloride');
insert into BRAND (id, name) values (281, 'Topiramate');
insert into BRAND (id, name) values (282, 'DEMEROL');
insert into BRAND (id, name) values (283, 'Jakemans Cherry');
insert into BRAND (id, name) values (284, 'Sulfamethoxazole and Trimethoprim');
insert into BRAND (id, name) values (285, 'Sodium Chloride');
insert into BRAND (id, name) values (286, 'CYCLOPHOSPHAMIDE');
insert into BRAND (id, name) values (287, 'Fresh Prep Laxative');
insert into BRAND (id, name) values (288, 'Amoxicillin and Clavulanate Potassium');
insert into BRAND (id, name) values (289, 'Isopropyl Alcohol');
insert into BRAND (id, name) values (290, 'CACTUS FLOWER AND MANGO ANTIBACTERIAL GENTLE FOAMING HAND SP');
insert into BRAND (id, name) values (291, 'BUSPIRONE HCl');
insert into BRAND (id, name) values (292, 'Lidocaine Viscous');
insert into BRAND (id, name) values (293, 'Acid Detox');
insert into BRAND (id, name) values (294, 'Borrelia Remedy');
insert into BRAND (id, name) values (295, 'POLYPHENOL C15 BROAD SPECTRUM SPF20 ANTI-WRINKLE PROTECT FLUID');
insert into BRAND (id, name) values (296, 'Nettle Pollen');
insert into BRAND (id, name) values (297, 'Cholestyramine');
insert into BRAND (id, name) values (298, 'Oxymorphone Hydrochloride');
insert into BRAND (id, name) values (299, 'Ibuprofen');
insert into BRAND (id, name) values (300, 'Enalapril Maleate');
insert into BRAND (id, name) values (301, 'Testosterone');
insert into BRAND (id, name) values (302, 'Ondansetron');
insert into BRAND (id, name) values (303, 'TOPIRAMATE');
insert into BRAND (id, name) values (304, 'Albuterol Sulfate');
insert into BRAND (id, name) values (305, 'Oxygen');
insert into BRAND (id, name) values (306, 'GAVILAX');
insert into BRAND (id, name) values (307, 'TetraStem');
insert into BRAND (id, name) values (308, 'Meadow Fescue Grass, Standardized');
insert into BRAND (id, name) values (309, 'Potassium Chloride');
insert into BRAND (id, name) values (310, 'TRICLOSAN');
insert into BRAND (id, name) values (311, 'Folotyn');
insert into BRAND (id, name) values (312, 'Skin Rashes Eczema');
insert into BRAND (id, name) values (313, 'Lidocaine');
insert into BRAND (id, name) values (314, 'Impact Fix Pure Essence Foundation');
insert into BRAND (id, name) values (315, 'Moisturizing Hand Sanitizer');
insert into BRAND (id, name) values (316, 'Pollens - Trees, Willow, Black Salix nigra');
insert into BRAND (id, name) values (317, 'Orange');
insert into BRAND (id, name) values (318, 'HOME ANTIBACTERIAL');
insert into BRAND (id, name) values (319, 'Cialis');
insert into BRAND (id, name) values (320, 'Standardized Grass Pollen, Bermuda Grass');
insert into BRAND (id, name) values (321, 'Platinum for Men');
insert into BRAND (id, name) values (322, 'CENTER-AL - AMBROSIA TRIFIDA POLLEN');
insert into BRAND (id, name) values (323, 'Ritussin Expectorant');
insert into BRAND (id, name) values (324, 'Motion Medicine');
insert into BRAND (id, name) values (325, 'Omeprazole');
insert into BRAND (id, name) values (326, 'Good Neighbor Pharmacy Pain Relief');
insert into BRAND (id, name) values (327, 'BZK Swab');
insert into BRAND (id, name) values (328, 'Day Time Cold Multi-Symptom Cool Blast');
insert into BRAND (id, name) values (329, 'Prednisone');
insert into BRAND (id, name) values (330, 'Didanosine');
insert into BRAND (id, name) values (331, 'Skin antisepsis, oral cleansing, nasal antisepsis');
insert into BRAND (id, name) values (332, 'Neti Mist Sinus Spray');
insert into BRAND (id, name) values (333, 'Dextroamphetamine Saccharate, Amphetamine Aspartate, Dextroamphetamine Sulfate and Amphetamine Sulfate');
insert into BRAND (id, name) values (334, 'Rite Aid Extra Strength Pain Relief Cold and Hot Medicated');
insert into BRAND (id, name) values (335, 'Arnica e rad. 20');
insert into BRAND (id, name) values (336, 'Nervousness - Anxiety');
insert into BRAND (id, name) values (337, 'nicotine');
insert into BRAND (id, name) values (338, 'GoodStuff');
insert into BRAND (id, name) values (339, 'SORIATANE');
insert into BRAND (id, name) values (340, 'Strep Throat');
insert into BRAND (id, name) values (341, 'Alprazolam');
insert into BRAND (id, name) values (342, 'Salagen');
insert into BRAND (id, name) values (343, 'Thyrolar');
insert into BRAND (id, name) values (344, 'Vimovo');
insert into BRAND (id, name) values (345, 'Ramipril');
insert into BRAND (id, name) values (346, 'Covergirl Queen Collection All Day Flawless 3in1 Foundation');
insert into BRAND (id, name) values (347, 'lisinopril');
insert into BRAND (id, name) values (348, 'TRISPEC DMX Pediatric Drops Cough Suppressant Expectorant CHERRY RASPBERRY Flavor');
insert into BRAND (id, name) values (349, 'Amlodipine Besylate and Benazepril Hydrochloride');
insert into BRAND (id, name) values (350, 'Glycopyrrolate');
insert into BRAND (id, name) values (351, 'cough and chest congestion dm max');
insert into BRAND (id, name) values (352, 'ENJUVIA');
insert into BRAND (id, name) values (353, 'Treatment Set TS331810');
insert into BRAND (id, name) values (354, 'Quinidine Gluconate');
insert into BRAND (id, name) values (355, 'Tolnaftate');
insert into BRAND (id, name) values (356, 'Monoket');
insert into BRAND (id, name) values (357, 'ciprofloxacin');
insert into BRAND (id, name) values (358, 'LBEL divine lip gloss SPF 15');
insert into BRAND (id, name) values (359, 'Valacyclovir Hydrochloride');
insert into BRAND (id, name) values (360, 'Sulfamethoxazole and Trimethoprim');
insert into BRAND (id, name) values (361, 'Dyrenium');
insert into BRAND (id, name) values (362, 'Hydroxyzine Hydrochloride');
insert into BRAND (id, name) values (363, 'ZOLPIDEM TARTRATE');
insert into BRAND (id, name) values (364, 'Ethosuximide');
insert into BRAND (id, name) values (365, 'Articulatio genus 8');
insert into BRAND (id, name) values (366, 'False Ragweed');
insert into BRAND (id, name) values (367, 'Famotidine');
insert into BRAND (id, name) values (368, 'Oxygen');
insert into BRAND (id, name) values (369, 'Vicks DayQuil');
insert into BRAND (id, name) values (370, 'EXENCE WHITE');
insert into BRAND (id, name) values (371, 'OXYGEN');
insert into BRAND (id, name) values (372, 'GH Flex');
insert into BRAND (id, name) values (373, 'ADVIL PM');
insert into BRAND (id, name) values (374, 'AVAPRO');
insert into BRAND (id, name) values (375, 'All Day Allergy Relief');
insert into BRAND (id, name) values (376, 'Medicated Acne Pads');
insert into BRAND (id, name) values (377, 'MAXFIT FREEZE GEL');
insert into BRAND (id, name) values (378, 'dg health milk of magnesia');
insert into BRAND (id, name) values (379, 'CARBO VEGETABILIS');
insert into BRAND (id, name) values (380, 'Pain Relief Extra Strength');
insert into BRAND (id, name) values (381, 'HEALTHCARE Instant Hand Sanitizer Vanilla Scent');
insert into BRAND (id, name) values (382, 'Methocarbamol');
insert into BRAND (id, name) values (383, 'Oracit');
insert into BRAND (id, name) values (384, 'Mucus-Clear');
insert into BRAND (id, name) values (385, 'Pollens - Trees, Hickory, Shagbark Carya ovata');
insert into BRAND (id, name) values (386, 'Parrot Head Fins Up Sport 30 Mist');
insert into BRAND (id, name) values (387, 'Synthroid');
insert into BRAND (id, name) values (388, 'Triamcinolone Acetonide');
insert into BRAND (id, name) values (389, 'Nitrogen');
insert into BRAND (id, name) values (390, 'Acetaminophen');
insert into BRAND (id, name) values (391, 'Pier 1 Imports Ocean Water Anti-bacterial Hand Wash');
insert into BRAND (id, name) values (392, 'ARTEMISIA VULGARIS POLLEN');
insert into BRAND (id, name) values (393, 'BENAZEPRIL HYDROCHLORIDE');
insert into BRAND (id, name) values (394, 'Strattera');
insert into BRAND (id, name) values (395, 'sunmark');
insert into BRAND (id, name) values (396, 'Ampicillin');
insert into BRAND (id, name) values (397, 'HydrALAZINE Hydrochloride');
insert into BRAND (id, name) values (398, 'TRAZODONE');
insert into BRAND (id, name) values (399, 'THROMBIN-JMI');
insert into BRAND (id, name) values (400, 'Avon Elements');
insert into BRAND (id, name) values (401, 'NARS FOUNDATION');
insert into BRAND (id, name) values (402, 'Apizelen');
insert into BRAND (id, name) values (403, 'ORCHID');
insert into BRAND (id, name) values (404, 'Baclofen');
insert into BRAND (id, name) values (405, 'mally Face Defender Foundation');
insert into BRAND (id, name) values (406, 'H-Insomnia Formula');
insert into BRAND (id, name) values (407, 'KETOROLAC TROMETHAMINE');
insert into BRAND (id, name) values (408, 'RAZADYNE');
insert into BRAND (id, name) values (409, 'Dolce and Gabbana The Lift Foundation Natural Beige 120');
insert into BRAND (id, name) values (410, 'Felodipine');
insert into BRAND (id, name) values (411, 'Abstral');
insert into BRAND (id, name) values (412, 'SoundBody Advanced Relief');
insert into BRAND (id, name) values (413, 'Loratadine and Pseudoephedrine Sulfate');
insert into BRAND (id, name) values (414, 'Metadate CD');
insert into BRAND (id, name) values (415, 'Cevimeline Hydrochloride');
insert into BRAND (id, name) values (416, 'QUERCUS ALBA POLLEN');
insert into BRAND (id, name) values (417, 'Indomethacin');
insert into BRAND (id, name) values (418, 'Antibactierial Hand Sanitizer');
insert into BRAND (id, name) values (419, 'ACTIVE RESURGENCE TONER');
insert into BRAND (id, name) values (420, 'Coppertone Kids');
insert into BRAND (id, name) values (421, 'Isopropyl Alcohol');
insert into BRAND (id, name) values (422, 'AllergyEase Rocky Mtns');
insert into BRAND (id, name) values (423, 'Wheat Smut');
insert into BRAND (id, name) values (424, 'Naproxen Sodium');
insert into BRAND (id, name) values (425, 'Neupro');
insert into BRAND (id, name) values (426, 'Strattera');
insert into BRAND (id, name) values (427, 'Western Wheatgrass');
insert into BRAND (id, name) values (428, 'CEFTRIAXONE');
insert into BRAND (id, name) values (429, 'Lisinopril');
insert into BRAND (id, name) values (430, 'Humira');
insert into BRAND (id, name) values (431, 'Topiclear Xtra beauty');
insert into BRAND (id, name) values (432, 'Dexamethasone');
insert into BRAND (id, name) values (433, 'Fentanyl');
insert into BRAND (id, name) values (434, 'Horse Fly');
insert into BRAND (id, name) values (435, 'Fluorouracil');
insert into BRAND (id, name) values (436, 'Neomycin Polymyxin B Sulfates and Dexamethasone');
insert into BRAND (id, name) values (437, 'Valacyclovir Hydrochloride');
insert into BRAND (id, name) values (438, 'No7 Protect and Perfect Hand Cream Sunscreen Broad Spectrum SPF 15');
insert into BRAND (id, name) values (439, 'Coralite Extra Strength Menthol Pain Relief Sleeve - WRIST');
insert into BRAND (id, name) values (440, 'Childrens Pain Relief Grape');
insert into BRAND (id, name) values (441, 'CaraDerma');
insert into BRAND (id, name) values (442, 'REDNESS SOLUTIONS MAKEUP');
insert into BRAND (id, name) values (443, 'Varicose Veins');
insert into BRAND (id, name) values (444, 'WESTERN FAMILY HEMORRHOIDAL');
insert into BRAND (id, name) values (445, 'Olanzapine');
insert into BRAND (id, name) values (446, 'Oxygen');
insert into BRAND (id, name) values (447, 'Feather Mixture');
insert into BRAND (id, name) values (448, 'berkley and jensen nicotine');
insert into BRAND (id, name) values (449, 'Thioridazine Hydrochloride');
insert into BRAND (id, name) values (450, 'Aveeno Positively Radiant CC');
insert into BRAND (id, name) values (451, 'Solodyn');
insert into BRAND (id, name) values (452, 'Nitrous Oxide');
insert into BRAND (id, name) values (453, 'COLDS NAUSEA VOMITING');
insert into BRAND (id, name) values (454, 'Sheer Finish Tinted Moisturizer Light');
insert into BRAND (id, name) values (455, 'Bodycology white gardenia anti-bacterial scrubbing hand soap');
insert into BRAND (id, name) values (456, 'maximum strength');
insert into BRAND (id, name) values (457, 'Amlodipine besylate and Atorvastatin calcium');
insert into BRAND (id, name) values (458, 'ENALAPRIL MALEATE');
insert into BRAND (id, name) values (459, 'All Day');
insert into BRAND (id, name) values (460, 'CALCITONIN SALMON');
insert into BRAND (id, name) values (461, 'Allergy');
insert into BRAND (id, name) values (462, 'Sani Mousse');
insert into BRAND (id, name) values (463, 'THE HISTORY OF WHOO GONG JIN HYANG HAE YOON SUN');
insert into BRAND (id, name) values (464, 'Fluticasone');
insert into BRAND (id, name) values (465, 'EXALGO');
insert into BRAND (id, name) values (466, 'Deep Tan Perfecting Makeup Broad Spectrum SPF 25');
insert into BRAND (id, name) values (467, 'Brevital Sodium');
insert into BRAND (id, name) values (468, 'Corn Smut');
insert into BRAND (id, name) values (469, 'Gas - Indigestion');
insert into BRAND (id, name) values (470, 'IBU');
insert into BRAND (id, name) values (471, 'CRH Medsense Bisacodyl Stimulant Laxative');
insert into BRAND (id, name) values (472, 'Hemorrhoidal');
insert into BRAND (id, name) values (473, 'Oxacillin');
insert into BRAND (id, name) values (474, 'Glyburide and Metformin Hydrochloride');
insert into BRAND (id, name) values (475, 'Nabumetone');
insert into BRAND (id, name) values (476, 'Rite Aid');
insert into BRAND (id, name) values (477, 'Ranitidine');
insert into BRAND (id, name) values (478, 'CALC PHOS');
insert into BRAND (id, name) values (479, 'Cefprozil');
insert into BRAND (id, name) values (480, 'Carvedilol');
insert into BRAND (id, name) values (481, 'Nitrofurantoin Monohydrate/Macrocrystals');
insert into BRAND (id, name) values (482, 'Losartan Potassium');
insert into BRAND (id, name) values (483, 'H-Arthritis Formula');
insert into BRAND (id, name) values (484, 'acid controller');
insert into BRAND (id, name) values (485, 'CLINIQUE');
insert into BRAND (id, name) values (486, 'Diclofenac Sodium');
insert into BRAND (id, name) values (487, 'Citrus Burst Antibacterial Cleansing Hand Wash');
insert into BRAND (id, name) values (488, '3LAB PERFECT Sunscreen SPF 50 Plus Broad Spectrum');
insert into BRAND (id, name) values (489, 'buprenorphine hydrochloride and naloxone hydrochloride dihydrate');
insert into BRAND (id, name) values (490, 'Extra Strength Pain Reliever');
insert into BRAND (id, name) values (491, 'Treatment Set TS346698');
insert into BRAND (id, name) values (492, 'SINGULAIR');
insert into BRAND (id, name) values (493, 'GOOD NEIGHBOR PHARMACY CAPSAICIN');
insert into BRAND (id, name) values (494, 'Sotalol Hydrochloride');
insert into BRAND (id, name) values (495, 'Leader Allergy D 12');
insert into BRAND (id, name) values (496, 'Mustard');
insert into BRAND (id, name) values (497, 'Head Cold');
insert into BRAND (id, name) values (498, 'Moist SURE');
insert into BRAND (id, name) values (499, 'Nifedipine');
insert into BRAND (id, name) values (500, 'Sore Throat');
insert into BRAND (id, name) values (501, 'Cefprozil');
insert into BRAND (id, name) values (502, 'PRIMAXIN');
insert into BRAND (id, name) values (503, 'Instant Hand Sanitizer');
insert into BRAND (id, name) values (504, 'OMNIPAQUE');
insert into BRAND (id, name) values (505, 'LUXIQ');
insert into BRAND (id, name) values (506, 'Anti-Bacterial Hand');
insert into BRAND (id, name) values (507, 'Ruta Graveolens');
insert into BRAND (id, name) values (508, 'Plasbumin');
insert into BRAND (id, name) values (509, 'Olanzapine');
insert into BRAND (id, name) values (510, 'ESIKA PERFECT SKIN COVERAGE CONCEALER SPF 17');
insert into BRAND (id, name) values (511, 'Triamterene and Hydrochlorothiazide');
insert into BRAND (id, name) values (512, 'Metoprolol Tartrate');
insert into BRAND (id, name) values (513, 'Rugby Nasal Decongestant');
insert into BRAND (id, name) values (514, 'foundcealer 2-in-1 foundation and concealer Broad Spectrum SPF 15 Sunscreen');
insert into BRAND (id, name) values (515, 'GAMMAKED');
insert into BRAND (id, name) values (516, 'Miconazole Nitrate');
insert into BRAND (id, name) values (517, 'Anti-Bacterial Hand');
insert into BRAND (id, name) values (518, 'Trandolapril');
insert into BRAND (id, name) values (519, 'Ofloxacin');
insert into BRAND (id, name) values (520, 'Fluocinolone Acetonide');
insert into BRAND (id, name) values (521, 'INVEGA SUSTENNA');
insert into BRAND (id, name) values (522, 'Good Sense Nasal Four');
insert into BRAND (id, name) values (523, 'Secura Protective');
insert into BRAND (id, name) values (524, 'Proactiv');
insert into BRAND (id, name) values (525, 'Quetiapine Fumarate');
insert into BRAND (id, name) values (526, 'Dantrolene Sodium');
insert into BRAND (id, name) values (527, 'Clonazepam');
insert into BRAND (id, name) values (528, 'Smart Sense');
insert into BRAND (id, name) values (529, 'Terrasil Wart Treatment');
insert into BRAND (id, name) values (530, 'Parafon DSC');
insert into BRAND (id, name) values (531, 'ESOPINIO FRESH AND CLEAR FOUNDATION');
insert into BRAND (id, name) values (532, 'COUMADIN');
insert into BRAND (id, name) values (533, 'Lymphoplex');
insert into BRAND (id, name) values (534, 'CENTER-AL - FESTUCA PRATENSIS POLLEN');
insert into BRAND (id, name) values (535, 'Lornamead');
insert into BRAND (id, name) values (536, 'Rasuvo');
insert into BRAND (id, name) values (537, 'Acid Reducer');
insert into BRAND (id, name) values (538, 'PYtest');
insert into BRAND (id, name) values (539, 'Equate Menthol extra strength');
insert into BRAND (id, name) values (540, 'Ampicillin and Sulbactam');
insert into BRAND (id, name) values (541, 'Axe');
insert into BRAND (id, name) values (542, 'Coralite Extra Strength Menthol Pain Relief Sleeve - WRIST');
insert into BRAND (id, name) values (543, 'Cefazolin');
insert into BRAND (id, name) values (544, 'Suave');
insert into BRAND (id, name) values (545, 'LBEL Couleur luxe rouge irresistible maximum hydration SPF 17');
insert into BRAND (id, name) values (546, 'ANTIBACTERIAL HAND SANITIZER');
insert into BRAND (id, name) values (547, 'Abstral');
insert into BRAND (id, name) values (548, 'Primlev');
insert into BRAND (id, name) values (549, 'Whitening');
insert into BRAND (id, name) values (550, 'ALPHAGAN P');
insert into BRAND (id, name) values (551, 'Loperamide Hydrochloride');
insert into BRAND (id, name) values (552, 'Sumatriptan Succinate');
insert into BRAND (id, name) values (553, 'Nivea A Kiss of Shimmer Radiant Lip Care');
insert into BRAND (id, name) values (554, 'DIDREX');
insert into BRAND (id, name) values (555, 'CLARINS Extra-Comfort Broad Spectrum SPF 15 Sunscreen Tint 109');
insert into BRAND (id, name) values (556, 'ISENTRESS');
insert into BRAND (id, name) values (557, 'Unithroid');
insert into BRAND (id, name) values (558, 'Borago Nicotiana');
insert into BRAND (id, name) values (559, 'Fenoprofen Calcium');
insert into BRAND (id, name) values (560, 'CASUARINA EQUISETIFOLIA POLLEN');
insert into BRAND (id, name) values (561, 'Bum Ease');
insert into BRAND (id, name) values (562, 'Exuviance CoverBlend Skin Caring Foundation');
insert into BRAND (id, name) values (563, 'Anti-Aging Hydra Tint SPF 20 Shade 40');
insert into BRAND (id, name) values (564, 'CARVEDILOL');
insert into BRAND (id, name) values (565, 'Hydrogen Peroxide');
insert into BRAND (id, name) values (566, 'Desquam-X Wash');
insert into BRAND (id, name) values (567, 'Duavee');
insert into BRAND (id, name) values (568, 'BOTANICAL VANILLA FOUNDATION');
insert into BRAND (id, name) values (569, 'Serotonin');
insert into BRAND (id, name) values (570, 'California Black Oak');
insert into BRAND (id, name) values (571, 'AMOXICILLIN');
insert into BRAND (id, name) values (572, 'Oxandrolone');
insert into BRAND (id, name) values (573, 'HYDROXYZINE HYDROCHLORIDE');
insert into BRAND (id, name) values (574, 'Halonate Pac');
insert into BRAND (id, name) values (575, 'Loratadine');
insert into BRAND (id, name) values (576, 'LUXIQ');
insert into BRAND (id, name) values (577, 'Metolazone');
insert into BRAND (id, name) values (578, 'Dye-Free Childrens Acetaminophen Grape');
insert into BRAND (id, name) values (579, 'Sorbitol');
insert into BRAND (id, name) values (580, 'DIMETHICONE and ZINC OXIDE');
insert into BRAND (id, name) values (581, 'up and up minoxidil');
insert into BRAND (id, name) values (582, 'V-Natal');
insert into BRAND (id, name) values (583, 'Ecolab');
insert into BRAND (id, name) values (584, 'DIETHYLPROPION HYDROCHLORIDE');
insert into BRAND (id, name) values (585, 'Antacid');
insert into BRAND (id, name) values (586, 'CareOne Daytime Severe Cold and Cough');
insert into BRAND (id, name) values (587, 'Nigrospora sphaerica');
insert into BRAND (id, name) values (588, 'BuPROPion Hydrochloride');
insert into BRAND (id, name) values (589, 'Pleo Stroph');
insert into BRAND (id, name) values (590, 'Laxative');
insert into BRAND (id, name) values (591, 'Zetia');
insert into BRAND (id, name) values (592, 'BABY ANBESOL');
insert into BRAND (id, name) values (593, 'Hand Sanitizer');
insert into BRAND (id, name) values (594, 'Trimethoprim');
insert into BRAND (id, name) values (595, 'Acid Controller Complete');
insert into BRAND (id, name) values (596, 'Furosemide');
insert into BRAND (id, name) values (597, 'BiDil');
insert into BRAND (id, name) values (598, 'Ropinirole Hydrochloride');
insert into BRAND (id, name) values (599, 'UV Shield SPF 42');
insert into BRAND (id, name) values (600, 'Olanzapine');
insert into BRAND (id, name) values (601, 'Dexamethasone Sodium Phosphate');
insert into BRAND (id, name) values (602, 'Hand Sanitizer');
insert into BRAND (id, name) values (603, 'Moisture Renew');
insert into BRAND (id, name) values (604, 'ERY-TAB');
insert into BRAND (id, name) values (605, 'Rheumatic - Joint Care');
insert into BRAND (id, name) values (606, 'Sensodyne');
insert into BRAND (id, name) values (607, 'Propranolol Hydrochloride');
insert into BRAND (id, name) values (608, 'Equate Tussin');
insert into BRAND (id, name) values (609, 'Aspirin');
insert into BRAND (id, name) values (610, 'ciprofloxacin');
insert into BRAND (id, name) values (611, 'Butorphanol Tartrate');
insert into BRAND (id, name) values (612, 'Ceramide Lift And Firm Makeup Broad Spectrum Sunscreen SPF 15 Toast');
insert into BRAND (id, name) values (613, 'Ciprofloxacin');
insert into BRAND (id, name) values (614, 'Amlodipine besylate');
insert into BRAND (id, name) values (615, 'Psoriasis');
insert into BRAND (id, name) values (616, 'Firmarine Moisturizer SPF 30');
insert into BRAND (id, name) values (617, 'Hand wash');
insert into BRAND (id, name) values (618, 'Aminosyn II with Electrolytes');
insert into BRAND (id, name) values (619, 'BABYGANICS ECZEMA');
insert into BRAND (id, name) values (620, 'Oxaprozin');
insert into BRAND (id, name) values (621, 'CLARINS Broad Spectrum SPF 30 Sunscreen For Face Wrinkle Control');
insert into BRAND (id, name) values (622, 'ConRx Extra Strength');
insert into BRAND (id, name) values (623, 'hemorrhoidal');
insert into BRAND (id, name) values (624, 'Oxygen');
insert into BRAND (id, name) values (625, 'Metronidazole');
insert into BRAND (id, name) values (626, 'Fluorouracil');
insert into BRAND (id, name) values (627, 'First Mark');
insert into BRAND (id, name) values (628, 'Metronidazole');
insert into BRAND (id, name) values (629, 'Lil Drug Store NoSnooze');
insert into BRAND (id, name) values (630, 'Norvasc');
insert into BRAND (id, name) values (631, 'Sciatica - Nerve Care');
insert into BRAND (id, name) values (632, 'Lidocaine Hydrochloride and Epinephrine');
insert into BRAND (id, name) values (633, 'Diphenhist');
insert into BRAND (id, name) values (634, 'Extended Phenytoin Sodium');
insert into BRAND (id, name) values (635, 'Qsymia');
insert into BRAND (id, name) values (636, 'Glycopyrrolate');
insert into BRAND (id, name) values (637, 'Bay Leaf');
insert into BRAND (id, name) values (638, 'Stool Softener');
insert into BRAND (id, name) values (639, 'Childrens Fever Reliever');
insert into BRAND (id, name) values (640, 'NIRAVAM');
insert into BRAND (id, name) values (641, 'Fludarabine Phosphate');
insert into BRAND (id, name) values (642, 'White Spruce Hand Sanitizer');
insert into BRAND (id, name) values (643, 'Purple Coneflower Sore Throat');
insert into BRAND (id, name) values (644, '12 hour decongestant');
insert into BRAND (id, name) values (645, 'Darby');
insert into BRAND (id, name) values (646, 'Sheer Confidence Antiperspirant Deodorant');
insert into BRAND (id, name) values (647, 'Gris-PEG');
insert into BRAND (id, name) values (648, 'Furosemide');
insert into BRAND (id, name) values (649, 'Bladder - Kidney');
insert into BRAND (id, name) values (650, 'Azithromycin');
insert into BRAND (id, name) values (651, 'Diclofenac Sodium');
insert into BRAND (id, name) values (652, 'Nan San MUSFLEX External Analgesic');
insert into BRAND (id, name) values (653, 'Wal-Dryl-D');
insert into BRAND (id, name) values (654, 'Propranolol Hydrochloride');
insert into BRAND (id, name) values (655, 'EPICOCCUM NIGRUM');
insert into BRAND (id, name) values (656, 'IPKN ARTISTS TOUCH BB 01 LIGHT');
insert into BRAND (id, name) values (657, 'Gabapentin');
insert into BRAND (id, name) values (658, 'LOSARTAN POTASSIUM');
insert into BRAND (id, name) values (659, 'VECURONIUM BROMIDE');
insert into BRAND (id, name) values (660, 'Menest');
insert into BRAND (id, name) values (661, 'PRIMAXIN');
insert into BRAND (id, name) values (662, 'Granisetron');
insert into BRAND (id, name) values (663, 'Gabapentin');
insert into BRAND (id, name) values (664, 'Good Sense Cold');
insert into BRAND (id, name) values (665, 'SOLAR SENSE CLEAR ZINC SUNSCREEN BROAD SPECTRUM SPF 50 Plus');
insert into BRAND (id, name) values (666, 'ALPRAZOLAM');
insert into BRAND (id, name) values (667, 'Sweet Potato');
insert into BRAND (id, name) values (668, 'AcneFree Body Clearing');
insert into BRAND (id, name) values (669, 'Halls');
insert into BRAND (id, name) values (670, 'temazepam');
insert into BRAND (id, name) values (671, 'Zidovudine');
insert into BRAND (id, name) values (672, 'ED-A-HIST PSE');
insert into BRAND (id, name) values (673, 'Heparin Sodium');
insert into BRAND (id, name) values (674, 'SHISEIDO SHEER MATIFYING COMPACT (REFILL)');
insert into BRAND (id, name) values (675, 'IBU');
insert into BRAND (id, name) values (676, 'Omeprazole');
insert into BRAND (id, name) values (677, 'Chlorpromazine Hydrochloride');
insert into BRAND (id, name) values (678, 'nasal mist');
insert into BRAND (id, name) values (679, 'Methocarbamol');
insert into BRAND (id, name) values (680, 'Metformin Hydrochloride');
insert into BRAND (id, name) values (681, 'Pain Relief');
insert into BRAND (id, name) values (682, 'A and D');
insert into BRAND (id, name) values (683, 'elements anti aging vitamin complex');
insert into BRAND (id, name) values (684, 'Australian Pine');
insert into BRAND (id, name) values (685, 'CIPRO');
insert into BRAND (id, name) values (686, 'Palmers Amaranth');
insert into BRAND (id, name) values (687, 'Kerasal');
insert into BRAND (id, name) values (688, 'ISOSORBIDE MONONITRATE');
insert into BRAND (id, name) values (689, 'Antiseptic Hand Sanitizer');
insert into BRAND (id, name) values (690, 'Anti-Gas');
insert into BRAND (id, name) values (691, 'Sheep Sorrel');
insert into BRAND (id, name) values (692, 'TopCare Daytime Severe Cold and Cough');
insert into BRAND (id, name) values (693, 'Kids Crest');
insert into BRAND (id, name) values (694, 'Technetium Tc99m Generator');
insert into BRAND (id, name) values (695, 'Trichoderma harzianam');
insert into BRAND (id, name) values (696, 'OXYCODONE HYDROCHLORIDE');
insert into BRAND (id, name) values (697, 'Propylthiouracil');
insert into BRAND (id, name) values (698, 'Keppra');
insert into BRAND (id, name) values (699, 'Calamine');
insert into BRAND (id, name) values (700, 'Sulfamethoxazole and Trimethoprim');
insert into BRAND (id, name) values (701, 'Fluphenazine Hydrochloride');
insert into BRAND (id, name) values (702, 'Acarbose');
insert into BRAND (id, name) values (703, 'Reprexain');
insert into BRAND (id, name) values (704, 'Honeydew Melon');
insert into BRAND (id, name) values (705, 'Ultra Lubricant Eye Drops');
insert into BRAND (id, name) values (706, 'Good Neighbor Pharmacy Pain Relief');
insert into BRAND (id, name) values (707, 'Multi-Symptom Wal-Phed PE Non-Drowsy');
insert into BRAND (id, name) values (708, 'CVS');
insert into BRAND (id, name) values (709, 'DiorSkin Nude 010 Ivory');
insert into BRAND (id, name) values (710, 'Albuterol');
insert into BRAND (id, name) values (711, 'Candida');
insert into BRAND (id, name) values (712, 'Clonazepam');
insert into BRAND (id, name) values (713, 'Loxapine');
insert into BRAND (id, name) values (714, 'Aveeno Active Naturals Skin Relief Calming');
insert into BRAND (id, name) values (715, 'Ciprofloxacin Hydrochloride');
insert into BRAND (id, name) values (716, 'Alka-Seltzer Plus');
insert into BRAND (id, name) values (717, 'Phisoderm Anti Blemish Body Wash');
insert into BRAND (id, name) values (718, 'LEVAQUIN');
insert into BRAND (id, name) values (719, 'Clonidine Hydrochloride');
insert into BRAND (id, name) values (720, 'GRAPHITES');
insert into BRAND (id, name) values (721, 'IMDUR');
insert into BRAND (id, name) values (722, 'wal itin d');
insert into BRAND (id, name) values (723, 'HYDROCODONE BITARTRATE AND ACETAMINOPHEN');
insert into BRAND (id, name) values (724, 'CVS pharmacy');
insert into BRAND (id, name) values (725, 'Nan San EASY FLEX Pain Relieving');
insert into BRAND (id, name) values (726, 'Guanfacine');
insert into BRAND (id, name) values (727, 'Acetaminophen Phenylephrine HCl');
insert into BRAND (id, name) values (728, 'Stool Softener');
insert into BRAND (id, name) values (729, 'Lidocaine Hydrochloride');
insert into BRAND (id, name) values (730, 'Medi-Cortisone');
insert into BRAND (id, name) values (731, 'ANTIBACTERIAL HAND SP WITH LIGHT MOISTURIZERS REFILL');
insert into BRAND (id, name) values (732, 'SMART SENSE');
insert into BRAND (id, name) values (733, 'Amitriptyline Hydrochloride');
insert into BRAND (id, name) values (734, 'LBEL REPLENISHING FOUNDATION SPF 14');
insert into BRAND (id, name) values (735, 'Salmon');
insert into BRAND (id, name) values (736, 'Chemtox');
insert into BRAND (id, name) values (737, 'Triamcinolone Acetonide');
insert into BRAND (id, name) values (738, 'Icy Hot');
insert into BRAND (id, name) values (739, 'Furosemide');
insert into BRAND (id, name) values (740, 'Levofloxacin');
insert into BRAND (id, name) values (741, 'UNDECYLENIC ACID');
insert into BRAND (id, name) values (742, 'Neutrogena Oil Free Acne Stress Control Night Cleansing Pads');
insert into BRAND (id, name) values (743, 'ECOSAVE JAPANESE CHERRY BLOSSOM SOAP ANTIBACTERIAL HAND SOAP');
insert into BRAND (id, name) values (744, 'Besivance');
insert into BRAND (id, name) values (745, 'Topcare Nicotine');
insert into BRAND (id, name) values (746, 'metoprolol succinate');
insert into BRAND (id, name) values (747, 'Sleep-Aid');
insert into BRAND (id, name) values (748, 'Perphenazine');
insert into BRAND (id, name) values (749, 'Levofloxacin');
insert into BRAND (id, name) values (750, 'Sleep RELIEF');
insert into BRAND (id, name) values (751, 'Prednisolone Sodium Phosphate');
insert into BRAND (id, name) values (752, 'Sani Professional Brand Sani-HandsInstant Hand Sani');
insert into BRAND (id, name) values (753, '3 CONCEPT EYES SLIM FIT PACT NATURAL IVORY');
insert into BRAND (id, name) values (754, 'Ramipril');
insert into BRAND (id, name) values (755, '7 Select Aspirin');
insert into BRAND (id, name) values (756, 'CLINIMIX E');
insert into BRAND (id, name) values (757, 'LAMISIL');
insert into BRAND (id, name) values (758, 'Ampicillin and Sulbactam');
insert into BRAND (id, name) values (759, 'Warfarin Sodium');
insert into BRAND (id, name) values (760, 'Focalin');
insert into BRAND (id, name) values (761, 'night time');
insert into BRAND (id, name) values (762, 'Fludrocortisone Acetate');
insert into BRAND (id, name) values (763, 'Divalproex Sodium');
insert into BRAND (id, name) values (764, 'CLEAR ACTION');
insert into BRAND (id, name) values (765, 'Meloxicam');
insert into BRAND (id, name) values (766, 'Red Pine');
insert into BRAND (id, name) values (767, 'Ramipril');
insert into BRAND (id, name) values (768, 'Niravam');
insert into BRAND (id, name) values (769, 'LidoPatch');
insert into BRAND (id, name) values (770, 'Alendronate Sodium');
insert into BRAND (id, name) values (771, 'Onmel');
insert into BRAND (id, name) values (772, 'Temozolomide');
insert into BRAND (id, name) values (773, 'Nettle Pollen');
insert into BRAND (id, name) values (774, 'Luffeel');
insert into BRAND (id, name) values (775, 'Haloperidol');
insert into BRAND (id, name) values (776, 'Amiodarone hydrochloride');
insert into BRAND (id, name) values (777, 'Eurax');
insert into BRAND (id, name) values (778, 'Armour Thyroid');
insert into BRAND (id, name) values (779, 'Sinus Relief');
insert into BRAND (id, name) values (780, 'health mart adult tussin');
insert into BRAND (id, name) values (781, 'Entre-S');
insert into BRAND (id, name) values (782, 'triCitrasol');
insert into BRAND (id, name) values (783, 'OSENI');
insert into BRAND (id, name) values (784, 'Xyzal');
insert into BRAND (id, name) values (785, 'Ear Inflammation Plus');
insert into BRAND (id, name) values (786, 'LEADER Triple Antibiotic');
insert into BRAND (id, name) values (787, 'TYLENOL Cold Multi-Symptom Daytime');
insert into BRAND (id, name) values (788, 'LAVIV');
insert into BRAND (id, name) values (789, 'OHUI THE FIRST CELL REVOLUTION AGE CONTROL SUN BLOCK');
insert into BRAND (id, name) values (790, 'equate nicotine');
insert into BRAND (id, name) values (791, 'Anti Diarrheal');
insert into BRAND (id, name) values (792, 'Aspirin');
insert into BRAND (id, name) values (793, 'ATORVASTATIN CALCIUM');
insert into BRAND (id, name) values (794, 'Homeopathic Sleep Formula');
insert into BRAND (id, name) values (795, 'Captopril');
insert into BRAND (id, name) values (796, 'clindamycin phosphate');
insert into BRAND (id, name) values (797, 'Hydromorphone Hydrochloride');
insert into BRAND (id, name) values (798, 'Chlorpheniramine maleate');
insert into BRAND (id, name) values (799, 'Prednisone');
insert into BRAND (id, name) values (800, 'Bactrim DS');
insert into BRAND (id, name) values (801, 'Defend Cold and Mucus');
insert into BRAND (id, name) values (802, 'Miconazole 7');
insert into BRAND (id, name) values (803, 'Diazepam');
insert into BRAND (id, name) values (804, 'INSTANT HAND SANITIZER');
insert into BRAND (id, name) values (805, 'Sennosides and Docusate Sodium');
insert into BRAND (id, name) values (806, 'Benzonatate');
insert into BRAND (id, name) values (807, 'pain and fever');
insert into BRAND (id, name) values (808, 'Metoprolol Tartrate');
insert into BRAND (id, name) values (809, 'Reliaderm');
insert into BRAND (id, name) values (810, 'Alprazolam');
insert into BRAND (id, name) values (811, 'Pain Relief PM');
insert into BRAND (id, name) values (812, 'Scott Triclosan Free Antibacterial Skin Cleanser');
insert into BRAND (id, name) values (813, 'Dextrose and Sodium Chloride');
insert into BRAND (id, name) values (814, 'Omeprazole and Sodium Bicarbonate');
insert into BRAND (id, name) values (815, 'Ear Care');
insert into BRAND (id, name) values (816, 'Coppertone Sensitive Skin');
insert into BRAND (id, name) values (817, 'Natural Fiber Powder');
insert into BRAND (id, name) values (818, 'UV Capture Vita Sun Gel');
insert into BRAND (id, name) values (819, 'Butalbital, Acetaminophen and Caffeine');
insert into BRAND (id, name) values (820, 'Laneige sliding pact EX');
insert into BRAND (id, name) values (821, 'Clindamycin hydrochloride');
insert into BRAND (id, name) values (822, 'Felodipine');
insert into BRAND (id, name) values (823, 'Duck Feathers');
insert into BRAND (id, name) values (824, 'Quetiapine Fumarate');
insert into BRAND (id, name) values (825, 'Prevage Anti Aging Moisture Broad Spectrum Sunscreen SPF 30');
insert into BRAND (id, name) values (826, 'TESTOSTERONE ENANTHATE');
insert into BRAND (id, name) values (827, 'Cough - Asthma');
insert into BRAND (id, name) values (828, 'Care One pain relief');
insert into BRAND (id, name) values (829, 'anti nausea');
insert into BRAND (id, name) values (830, 'Haloperidol Decanoate');
insert into BRAND (id, name) values (831, 'Pain Reliever');
insert into BRAND (id, name) values (832, 'Potassium Chloride in Dextrose and Sodium Chloride');
insert into BRAND (id, name) values (833, 'Sweet Daisy Antibacterial Hand Sanitizer');
insert into BRAND (id, name) values (834, 'DG BODY');
insert into BRAND (id, name) values (835, 'Tikosyn');
insert into BRAND (id, name) values (836, 'ESIKA');
insert into BRAND (id, name) values (837, 'Acyclovir');
insert into BRAND (id, name) values (838, 'Secret Antiperspirant');
insert into BRAND (id, name) values (839, 'OraLabs Cold Sore Treatment');
insert into BRAND (id, name) values (840, 'verapamil hydrochloride');
insert into BRAND (id, name) values (841, 'risperidone');
insert into BRAND (id, name) values (842, 'Oxygen');
insert into BRAND (id, name) values (843, 'SWEET POTATO');
insert into BRAND (id, name) values (844, 'NITROGEN');
insert into BRAND (id, name) values (845, 'Dark Circle');
insert into BRAND (id, name) values (846, 'Pristiq Extended-Release');
insert into BRAND (id, name) values (847, 'Olay Total Effects Tone Correcting');
insert into BRAND (id, name) values (848, 'Vivierskin Sunscreen');
insert into BRAND (id, name) values (849, 'Perfecting Liquid Foundation Fair');
insert into BRAND (id, name) values (850, 'PediaCare Infants Fever Reducer Grape');
insert into BRAND (id, name) values (851, 'PAXIL');
insert into BRAND (id, name) values (852, 'Aspergillus flavus');
insert into BRAND (id, name) values (853, 'Tula Tantrum Tamer');
insert into BRAND (id, name) values (854, 'Disney PRINCESS Antibacterial Hand Wipes');
insert into BRAND (id, name) values (855, 'Mupirocin');
insert into BRAND (id, name) values (856, 'Amazonian clay BB illuminating moisturizer Broad Spectrum SPF 15 Sunscreen');
insert into BRAND (id, name) values (857, 'clear lax');
insert into BRAND (id, name) values (858, 'Secura Protective');
insert into BRAND (id, name) values (859, 'ACEPHEN');
insert into BRAND (id, name) values (860, 'Oxcarbazepine');
insert into BRAND (id, name) values (861, 'Lombardy Poplar');
insert into BRAND (id, name) values (862, 'losartan potassium');
insert into BRAND (id, name) values (863, 'Losartan Potassium');
insert into BRAND (id, name) values (864, 'Graphites Kit Refill');
insert into BRAND (id, name) values (865, 'Quetiapine fumarate');
insert into BRAND (id, name) values (866, 'Ramipril');
insert into BRAND (id, name) values (867, 'Severe Cold and Flu');
insert into BRAND (id, name) values (868, 'Acetylcysteine');
insert into BRAND (id, name) values (869, 'Inflammation Therapy');
insert into BRAND (id, name) values (870, 'PAUL and JOE SILKY SMOOTH FOUNDATION UV 101');
insert into BRAND (id, name) values (871, 'RISPERDAL');
insert into BRAND (id, name) values (872, 'TAZTIA');
insert into BRAND (id, name) values (873, 'TUMS');
insert into BRAND (id, name) values (874, 'Topricin');
insert into BRAND (id, name) values (875, 'Virt-Vite Plus');
insert into BRAND (id, name) values (876, 'Megestrol Acetate');
insert into BRAND (id, name) values (877, 'RAZADYNE');
insert into BRAND (id, name) values (878, 'Formica Stibium comp. Special Order');
insert into BRAND (id, name) values (879, 'AMMONIUM PHOSPHORICUM');
insert into BRAND (id, name) values (880, 'H-Psoriasis Formula');
insert into BRAND (id, name) values (881, 'Didanosine');
insert into BRAND (id, name) values (882, 'Rhizopus oryzae');
insert into BRAND (id, name) values (883, 'Venlafaxine Hydrochloride');
insert into BRAND (id, name) values (884, 'Viagra');
insert into BRAND (id, name) values (885, 'Prochlorperazine Maleate');
insert into BRAND (id, name) values (886, 'Pantoprazole Sodium');
insert into BRAND (id, name) values (887, 'Conney Aspirin Free');
insert into BRAND (id, name) values (888, 'Menstrual Complete');
insert into BRAND (id, name) values (889, 'healthy accents cold and allergy');
insert into BRAND (id, name) values (890, 'Treatment Set TS333177');
insert into BRAND (id, name) values (891, 'BioFlexor');
insert into BRAND (id, name) values (892, 'Meniscus 6');
insert into BRAND (id, name) values (893, 'Venlafaxine Hydrochloride');
insert into BRAND (id, name) values (894, 'Sucralfate');
insert into BRAND (id, name) values (895, 'Mirtazapine');
insert into BRAND (id, name) values (896, 'SAMBUCUS FLUCARE');
insert into BRAND (id, name) values (897, 'Isomers Clear Skin Acne Treatment Gel');
insert into BRAND (id, name) values (898, 'Ultravist');
insert into BRAND (id, name) values (899, 'DULOXETINE');
insert into BRAND (id, name) values (900, 'Levothyroxine Sodium');
insert into BRAND (id, name) values (901, 'berkley and jensen nicotine');
insert into BRAND (id, name) values (902, 'Demerol');
insert into BRAND (id, name) values (903, 'Smart Sense NightTime Cold and Flu');
insert into BRAND (id, name) values (904, 'CY BETTER LIPS BALM Humectante para Labios con color FPS 18');
insert into BRAND (id, name) values (905, 'Hemorrhoidal');
insert into BRAND (id, name) values (906, 'oil');
insert into BRAND (id, name) values (907, 'Multi Vitamin and Fluoride');
insert into BRAND (id, name) values (908, 'CVS pharmacy');
insert into BRAND (id, name) values (909, 'Carvedilol');
insert into BRAND (id, name) values (910, 'Bupropion Hydrochloride');
insert into BRAND (id, name) values (911, 'HYDROCODONE BITARTRATE AND ACETAMINOPHEN');
insert into BRAND (id, name) values (912, 'benzonatate');
insert into BRAND (id, name) values (913, 'Hydromorphone Hydrochloride');
insert into BRAND (id, name) values (914, 'Oticin');
insert into BRAND (id, name) values (915, 'Tekturna');
insert into BRAND (id, name) values (916, 'Vaseline');
insert into BRAND (id, name) values (917, 'GOONG SECRET MILD SUN');
insert into BRAND (id, name) values (918, 'Thyroid');
insert into BRAND (id, name) values (919, 'CILOSTAZOL');
insert into BRAND (id, name) values (920, 'Virginia Live Oak');
insert into BRAND (id, name) values (921, 'Oxygen');
insert into BRAND (id, name) values (922, 'Petrolatum');
insert into BRAND (id, name) values (923, 'Tussin Cough and Chest Congestion DM');
insert into BRAND (id, name) values (924, 'Acyclovir');
insert into BRAND (id, name) values (925, 'Peptic Relief');
insert into BRAND (id, name) values (926, 'Potassium Acetate');
insert into BRAND (id, name) values (927, 'Tegretol');
insert into BRAND (id, name) values (928, 'Ketoprofen');
insert into BRAND (id, name) values (929, 'Losartan Potassium');
insert into BRAND (id, name) values (930, 'TERUFLEX Blood Bag System Anticoagulant Citrate Phosphate Dextrose Adenine (CPDA-1)');
insert into BRAND (id, name) values (931, 'SENSAI FLUID FINISH FF202');
insert into BRAND (id, name) values (932, 'Zydelig');
insert into BRAND (id, name) values (933, 'Eye Wash');
insert into BRAND (id, name) values (934, 'FANAPT');
insert into BRAND (id, name) values (935, 'Cals 40 (Number 6)');
insert into BRAND (id, name) values (936, 'Pollens - Trees, Oak Mix');
insert into BRAND (id, name) values (937, 'Mary Kay Tinted Lip Balm Sunscreen SPF 15 Berry');
insert into BRAND (id, name) values (938, 'Aspirin');
insert into BRAND (id, name) values (939, 'Zepaseptic');
insert into BRAND (id, name) values (940, 'Penicillin V Potassium');
insert into BRAND (id, name) values (941, 'Loperamide Hydrochloride');
insert into BRAND (id, name) values (942, 'Motrin');
insert into BRAND (id, name) values (943, 'Pollens - Weeds and Garden Plants, Cocklebur Xanthium strumarium');
insert into BRAND (id, name) values (944, 'Secale Quartz');
insert into BRAND (id, name) values (945, 'Flu Relief Therapy Night Time');
insert into BRAND (id, name) values (946, 'Gillette Clinical Strength');
insert into BRAND (id, name) values (947, 'Multi Vitamin Infusion');
insert into BRAND (id, name) values (948, 'Lisinopril and hydrochlorothiazide');
insert into BRAND (id, name) values (949, 'Colds Earache');
insert into BRAND (id, name) values (950, 'Cyclobenzaprine Hydrochloride');
insert into BRAND (id, name) values (951, 'Pleo Poly G');
insert into BRAND (id, name) values (952, 'Metronidazole');
insert into BRAND (id, name) values (953, 'COLESTIPOL HYDROCHLORIDE');
insert into BRAND (id, name) values (954, 'Hydrocodone Bitartrate And Acetaminophen');
insert into BRAND (id, name) values (955, 'Strattera');
insert into BRAND (id, name) values (956, 'Oxygen');
insert into BRAND (id, name) values (957, 'Multitrace-5');
insert into BRAND (id, name) values (958, 'SHISEIDO FUTURE SOLUTION LX TOTAL RADIANCE FOUNDATION');
insert into BRAND (id, name) values (959, 'FormuCare Nasal Spray');
insert into BRAND (id, name) values (960, 'Ondansetron');
insert into BRAND (id, name) values (961, 'Olanzapine');
insert into BRAND (id, name) values (962, 'Soft and Silky Antiseptic');
insert into BRAND (id, name) values (963, 'Colyte');
insert into BRAND (id, name) values (964, 'Vital Weight Loss');
insert into BRAND (id, name) values (965, 'GENTLE REJUVENATION SYSTEM');
insert into BRAND (id, name) values (966, 'Assured Night time Cold and Cough');
insert into BRAND (id, name) values (967, 'Terbinafine Hydrochloride');
insert into BRAND (id, name) values (968, 'Reguloid');
insert into BRAND (id, name) values (969, 'TOURCIA');
insert into BRAND (id, name) values (970, 'Nytol');
insert into BRAND (id, name) values (971, 'SulfaCleanse 8/4');
insert into BRAND (id, name) values (972, 'Slim Remedy No. 15');
insert into BRAND (id, name) values (973, 'COUMADIN');
insert into BRAND (id, name) values (974, 'Flomax');
insert into BRAND (id, name) values (975, 'Cefaclor');
insert into BRAND (id, name) values (976, 'Koh Gen Do Maifanshi Makeup Color Base');
insert into BRAND (id, name) values (977, 'Baclofen');
insert into BRAND (id, name) values (978, 'Brevibloc');
insert into BRAND (id, name) values (979, 'Severe Sinus Congestion');
insert into BRAND (id, name) values (980, 'Isosorbide Dinitrate');
insert into BRAND (id, name) values (981, 'Paroxetine');
insert into BRAND (id, name) values (982, 'Obao Men Audaz');
insert into BRAND (id, name) values (983, 'Carbon Dioxide');
insert into BRAND (id, name) values (984, 'VIGAMOX');
insert into BRAND (id, name) values (985, 'Trial Antacid');
insert into BRAND (id, name) values (986, 'Amantadine Hydrochloride');
insert into BRAND (id, name) values (987, 'Wormwood');
insert into BRAND (id, name) values (988, 'Hydroxyzine Pamoate');
insert into BRAND (id, name) values (989, 'Lovastatin');
insert into BRAND (id, name) values (990, 'Bodycology');
insert into BRAND (id, name) values (991, 'Levocarnitine');
insert into BRAND (id, name) values (992, 'Cenestin');
insert into BRAND (id, name) values (993, 'Isosorbide Sublingual');
insert into BRAND (id, name) values (994, 'meijer kids');
insert into BRAND (id, name) values (995, 'Ammonium Lactate');
insert into BRAND (id, name) values (996, 'Levocarnitine');
insert into BRAND (id, name) values (997, 'TERUFLEX Blood Bag System Anticoagulant Citrate Phosphate Dextrose Adenine (CPDA-1)');
insert into BRAND (id, name) values (998, 'Metformin Hydrochloride');
insert into BRAND (id, name) values (999, 'LEFLUNOMIDE');
insert into BRAND (id, name) values (1000, 'Trimethobenzamide Hydrochloride');
