insert into DELIVERY_CMP (id, name) values (1, 'Nuvigil');
insert into DELIVERY_CMP (id, name) values (2, 'Fanapt');
insert into DELIVERY_CMP (id, name) values (3, 'Pollens - Trees, Birch Mix');
insert into DELIVERY_CMP (id, name) values (4, 'donepezil hydrochloride');
insert into DELIVERY_CMP (id, name) values (5, 'Burweed Marsh Elder');
insert into DELIVERY_CMP (id, name) values (6, 'Levofloxacin');
insert into DELIVERY_CMP (id, name) values (7, 'UNNAPLAST');
insert into DELIVERY_CMP (id, name) values (8, 'Olanzapine');
insert into DELIVERY_CMP (id, name) values (9, 'Antiperspirant Cedarwood');
insert into DELIVERY_CMP (id, name) values (10, 'Naratriptan');
insert into DELIVERY_CMP (id, name) values (11, 'Diltiazem Hydrochloride');
insert into DELIVERY_CMP (id, name) values (12, 'Oculoheel');
insert into DELIVERY_CMP (id, name) values (13, 'good neighbor pharmacy cold head congestion');
insert into DELIVERY_CMP (id, name) values (14, 'Isopropyl Rubbing Alcohol');
insert into DELIVERY_CMP (id, name) values (15, 'Montelukast Sodium');
insert into DELIVERY_CMP (id, name) values (16, 'Clonidine Hydrochloride');
insert into DELIVERY_CMP (id, name) values (17, 'Pramipexole Dihydrochloride');
insert into DELIVERY_CMP (id, name) values (18, 'Sulwhasoo Lumitouch Foundation');
insert into DELIVERY_CMP (id, name) values (19, 'Everyday Facial Moisturizer And Sunscreen SPF 20');
insert into DELIVERY_CMP (id, name) values (20, 'Miconazole 7');
insert into DELIVERY_CMP (id, name) values (21, 'Instant Hand Sanitizer');
insert into DELIVERY_CMP (id, name) values (22, 'SPF 30 Sunscreen');
insert into DELIVERY_CMP (id, name) values (23, 'Buspirone Hydrochloride');
insert into DELIVERY_CMP (id, name) values (24, 'CENTUSSIN DHC');
insert into DELIVERY_CMP (id, name) values (25, 'Dexmethylphenidate Hydrochloride');
insert into DELIVERY_CMP (id, name) values (26, 'Hansan Spray');
insert into DELIVERY_CMP (id, name) values (27, 'Nivea For Men Protective');
insert into DELIVERY_CMP (id, name) values (28, 'Wash-Up Towelette');
insert into DELIVERY_CMP (id, name) values (29, 'ReCreate Foundation');
insert into DELIVERY_CMP (id, name) values (30, 'Zaleplon');
insert into DELIVERY_CMP (id, name) values (31, 'Lucky');
insert into DELIVERY_CMP (id, name) values (32, 'Lymph Drainage');
insert into DELIVERY_CMP (id, name) values (33, 'bareMinerals bareSkin Pure Brightening Serum Foundation Broad Spectrum SPF 20');
insert into DELIVERY_CMP (id, name) values (34, 'SUNZONE FAMILY SPF 60');
insert into DELIVERY_CMP (id, name) values (35, 'Cefprozil');
insert into DELIVERY_CMP (id, name) values (36, 'Double Antibiotic Plus Pain Relief');
insert into DELIVERY_CMP (id, name) values (37, 'Norditropin');
insert into DELIVERY_CMP (id, name) values (38, 'Mentox');
insert into DELIVERY_CMP (id, name) values (39, 'Levothyroxine Sodium');
insert into DELIVERY_CMP (id, name) values (40, 'Ranitidine');
insert into DELIVERY_CMP (id, name) values (41, 'Lidocaine Hydrochloride and Hydrocortisone Acetate');
insert into DELIVERY_CMP (id, name) values (42, 'Be gone Bruises and Bumps');
insert into DELIVERY_CMP (id, name) values (43, 'CLADOSPORIUM SPHAEROSPERMUM');
insert into DELIVERY_CMP (id, name) values (44, 'Asclera');
insert into DELIVERY_CMP (id, name) values (45, 'Animal Allergens, Feather Mix');
insert into DELIVERY_CMP (id, name) values (46, 'Brome Grass');
insert into DELIVERY_CMP (id, name) values (47, 'Image Essentials Hair Regrowth Treatment');
insert into DELIVERY_CMP (id, name) values (48, 'Losartan Potassium and Hydrochlorothiazide');
insert into DELIVERY_CMP (id, name) values (49, 'METOPROLOL SUCCINATE');
insert into DELIVERY_CMP (id, name) values (50, 'Dextroamphetamine saccharate, amphetamine aspartate monohydrate, dextroamphetamine sulfate, amphetamine sulfate');
insert into DELIVERY_CMP (id, name) values (51, 'Axe');
insert into DELIVERY_CMP (id, name) values (52, 'Etodolac');
insert into DELIVERY_CMP (id, name) values (53, 'DELFLEX');
insert into DELIVERY_CMP (id, name) values (54, 'Ofloxacin');
insert into DELIVERY_CMP (id, name) values (55, 'adult severe congestion and cough');
insert into DELIVERY_CMP (id, name) values (56, 'Octreotide acetate');
insert into DELIVERY_CMP (id, name) values (57, 'STANDARDIZED TIMOTHY GRASS POLLEN');
insert into DELIVERY_CMP (id, name) values (58, 'SYLVANT');
insert into DELIVERY_CMP (id, name) values (59, 'Zenzedi');
insert into DELIVERY_CMP (id, name) values (60, 'Cefdinir');
insert into DELIVERY_CMP (id, name) values (61, 'Butalbital, Acetaminophen, Caffeine, and Codeine Phosphate');
insert into DELIVERY_CMP (id, name) values (62, 'Testosterone Cypionate');
insert into DELIVERY_CMP (id, name) values (63, 'The Cover Classic Foundation');
insert into DELIVERY_CMP (id, name) values (64, 'Genuine First Aid Burn Antiseptic Pain Relief With Aloe');
insert into DELIVERY_CMP (id, name) values (65, 'Laxative for Women');
insert into DELIVERY_CMP (id, name) values (66, 'Health Smart Instant Hand Sanitizer with aloe vera and vitamin e sweet pea');
insert into DELIVERY_CMP (id, name) values (67, 'Oily SK Specific Solutions');
insert into DELIVERY_CMP (id, name) values (68, 'Raspberry');
insert into DELIVERY_CMP (id, name) values (69, 'Omeprazole');
insert into DELIVERY_CMP (id, name) values (70, 'Isopropyl Alcohol');
insert into DELIVERY_CMP (id, name) values (71, 'Pantoprazole Sodium');
insert into DELIVERY_CMP (id, name) values (72, 'OXYGEN');
insert into DELIVERY_CMP (id, name) values (73, 'Epicoccum nigrum');
insert into DELIVERY_CMP (id, name) values (74, 'Western Water Hemp');
insert into DELIVERY_CMP (id, name) values (75, 'No7 Stay Perfect Foundation Sunscreen SPF 15 New Ivory');
insert into DELIVERY_CMP (id, name) values (76, 'Cefdinir');
insert into DELIVERY_CMP (id, name) values (77, 'ANNA LOTAN Premium B.B. UVA UVB SPF 36');
insert into DELIVERY_CMP (id, name) values (78, 'Headache Restlessness');
insert into DELIVERY_CMP (id, name) values (79, 'Diflorasone Diacetate');
insert into DELIVERY_CMP (id, name) values (80, 'Vida Mia Hand Sanitizer Aloe Vera');
insert into DELIVERY_CMP (id, name) values (81, 'Amoxicillin');
insert into DELIVERY_CMP (id, name) values (82, 'Cefpodoxime Proxetil');
insert into DELIVERY_CMP (id, name) values (83, 'sunmark');
insert into DELIVERY_CMP (id, name) values (84, 'Food - Plant Source, Carrot Daucus carota');
insert into DELIVERY_CMP (id, name) values (85, 'Sore Throat Coughs');
insert into DELIVERY_CMP (id, name) values (86, 'Zyprexa');
insert into DELIVERY_CMP (id, name) values (87, 'Mirtazapine');
insert into DELIVERY_CMP (id, name) values (88, 'sotalol hydrochloride');
insert into DELIVERY_CMP (id, name) values (89, 'Pantoprazole Sodium');
insert into DELIVERY_CMP (id, name) values (90, 'DG Health Pain Relief');
insert into DELIVERY_CMP (id, name) values (91, 'Be gone Scars');
insert into DELIVERY_CMP (id, name) values (92, 'COUMADIN');
insert into DELIVERY_CMP (id, name) values (93, 'Crest Pro-Health');
insert into DELIVERY_CMP (id, name) values (94, 'Loratadine');
insert into DELIVERY_CMP (id, name) values (95, 'Mirtazapine');
insert into DELIVERY_CMP (id, name) values (96, 'HUSKY 515');
insert into DELIVERY_CMP (id, name) values (97, 'Levothyroxine Sodium');
insert into DELIVERY_CMP (id, name) values (98, 'Oxycodone Hydchloride');
insert into DELIVERY_CMP (id, name) values (99, 'GlucaGen');
insert into DELIVERY_CMP (id, name) values (100, 'Allscale');
insert into DELIVERY_CMP (id, name) values (101, 'Hydrogen Peroxide');
insert into DELIVERY_CMP (id, name) values (102, 'Quetiapine Fumarate');
insert into DELIVERY_CMP (id, name) values (103, 'hemorrhoidal');
insert into DELIVERY_CMP (id, name) values (104, 'BELLADONNA');
insert into DELIVERY_CMP (id, name) values (105, 'Naproxen Sodium');
insert into DELIVERY_CMP (id, name) values (106, 'Allergy Relief');
insert into DELIVERY_CMP (id, name) values (107, 'FUNGAL FREE NAILS');
insert into DELIVERY_CMP (id, name) values (108, 'Pure Transformation Sheer Tan');
insert into DELIVERY_CMP (id, name) values (109, 'Alprazolam');
insert into DELIVERY_CMP (id, name) values (110, 'Ciprofloxacin Hydrochloride');
insert into DELIVERY_CMP (id, name) values (111, 'Vancocin');
insert into DELIVERY_CMP (id, name) values (112, 'Super Aqua Ampoule');
insert into DELIVERY_CMP (id, name) values (113, 'Loblolly Pine');
insert into DELIVERY_CMP (id, name) values (114, 'Isosorbide Dinitrate');
insert into DELIVERY_CMP (id, name) values (115, 'Ativan');
insert into DELIVERY_CMP (id, name) values (116, 'Divalproex Sodium');
insert into DELIVERY_CMP (id, name) values (117, 'Quality Choice Vaginal Anti-Itch');
insert into DELIVERY_CMP (id, name) values (118, 'Losartan potassium and Hydrochlorothiazide');
insert into DELIVERY_CMP (id, name) values (119, 'Instant Hand Sanitizer - Strawberry Scented');
insert into DELIVERY_CMP (id, name) values (120, 'Pollens - Trees, Oak, Red Quercus rubra');
insert into DELIVERY_CMP (id, name) values (121, 'Dexamethasone Sodium Phosphate');
insert into DELIVERY_CMP (id, name) values (122, 'COUMADIN');
insert into DELIVERY_CMP (id, name) values (123, 'Moexipril Hydrochloride and Hydrochlorothiazide');
insert into DELIVERY_CMP (id, name) values (124, 'Waterless Hand Sanitizer');
insert into DELIVERY_CMP (id, name) values (125, 'Dove');
insert into DELIVERY_CMP (id, name) values (126, 'Clindamycin Palmitate Hydrochloride');
insert into DELIVERY_CMP (id, name) values (127, 'MEGA-C-ACID');
insert into DELIVERY_CMP (id, name) values (128, 'Triton HS-777');
insert into DELIVERY_CMP (id, name) values (129, 'Ultra Color Rich');
insert into DELIVERY_CMP (id, name) values (130, 'COLGATE PROCLINICAL - Sparkling Mint');
insert into DELIVERY_CMP (id, name) values (131, 'Propranolol Hydrochloride');
insert into DELIVERY_CMP (id, name) values (132, 'Phenazopyridine Hydrochloride');
insert into DELIVERY_CMP (id, name) values (133, 'Gas Relief');
insert into DELIVERY_CMP (id, name) values (134, 'Moisture Renew');
insert into DELIVERY_CMP (id, name) values (135, 'Skelaxin');
insert into DELIVERY_CMP (id, name) values (136, 'Valacyclovir Hydrochloride');
insert into DELIVERY_CMP (id, name) values (137, 'Pro-Den Rx');
insert into DELIVERY_CMP (id, name) values (138, 'DRY SORE THROAT');
insert into DELIVERY_CMP (id, name) values (139, 'Remedy Antifungal');
insert into DELIVERY_CMP (id, name) values (140, 'Stachybotrys');
insert into DELIVERY_CMP (id, name) values (141, 'Renacidin');
insert into DELIVERY_CMP (id, name) values (142, 'Healthy Wear Powder Foundation');
insert into DELIVERY_CMP (id, name) values (143, 'FocalinXR');
insert into DELIVERY_CMP (id, name) values (144, 'Day Time');
insert into DELIVERY_CMP (id, name) values (145, 'Environmental Adaptation Cold and Dry');
insert into DELIVERY_CMP (id, name) values (146, 'Amoxicillin and Clavulanate Potassium');
insert into DELIVERY_CMP (id, name) values (147, 'Pure Ivory Skin Defense Makeup SPF 15');
insert into DELIVERY_CMP (id, name) values (148, 'TRAMADOL HYDROCHLORIDE');
insert into DELIVERY_CMP (id, name) values (149, 'Bicalutamide');
insert into DELIVERY_CMP (id, name) values (150, 'Carvedilol');
insert into DELIVERY_CMP (id, name) values (151, 'Calming Skin');
insert into DELIVERY_CMP (id, name) values (152, 'Polyethylene Glycol 3350, NF Powder for Solution, Laxative');
insert into DELIVERY_CMP (id, name) values (153, 'Chlorpheniramine Maleate');
insert into DELIVERY_CMP (id, name) values (154, 'Hydroquinone');
insert into DELIVERY_CMP (id, name) values (155, 'Lansoprazole');
insert into DELIVERY_CMP (id, name) values (156, 'Theraflu');
insert into DELIVERY_CMP (id, name) values (157, 'Mefloquine Hydrochloride');
insert into DELIVERY_CMP (id, name) values (158, 'Colds Yellow Mucous');
insert into DELIVERY_CMP (id, name) values (159, 'PROMETHAZINE DM');
insert into DELIVERY_CMP (id, name) values (160, 'Quality Choice Daytime Severe Cold and Cough');
insert into DELIVERY_CMP (id, name) values (161, 'Childrens Allergy');
insert into DELIVERY_CMP (id, name) values (162, 'Benicar HCT');
insert into DELIVERY_CMP (id, name) values (163, 'MEDIQUE I-PRIN');
insert into DELIVERY_CMP (id, name) values (164, 'Medistik');
insert into DELIVERY_CMP (id, name) values (165, 'dalan GOLDEN TROPICS antibacterial deodorant');
insert into DELIVERY_CMP (id, name) values (166, 'Dexmethylphenidate Hydrochloride');
insert into DELIVERY_CMP (id, name) values (167, 'SHISEIDO REFINING MAKEUP PRIMER');
insert into DELIVERY_CMP (id, name) values (168, 'benzonatate');
insert into DELIVERY_CMP (id, name) values (169, 'Givenchy Photo Perfexion Fluid Foundation Broad Spectrum SPF 20 Perfect Cinnamon');
insert into DELIVERY_CMP (id, name) values (170, 'go wipes');
insert into DELIVERY_CMP (id, name) values (171, 'CONTROL DYNAMICS MATTIFYING');
insert into DELIVERY_CMP (id, name) values (172, 'Nighttime');
insert into DELIVERY_CMP (id, name) values (173, 'tussin dm');
insert into DELIVERY_CMP (id, name) values (174, 'MAKESENSE');
insert into DELIVERY_CMP (id, name) values (175, 'Gaba');
insert into DELIVERY_CMP (id, name) values (176, 'ZONISAMIDE');
insert into DELIVERY_CMP (id, name) values (177, 'GlucaGen HypoKit');
insert into DELIVERY_CMP (id, name) values (178, 'Lysol');
insert into DELIVERY_CMP (id, name) values (179, 'Potassium Chloride in Dextrose and Sodium Chloride');
insert into DELIVERY_CMP (id, name) values (180, 'Zaleplon');
insert into DELIVERY_CMP (id, name) values (181, 'Dove');
insert into DELIVERY_CMP (id, name) values (182, 'Everyday Clean Dandruff');
insert into DELIVERY_CMP (id, name) values (183, 'Ranitidine Hydrochloride');
insert into DELIVERY_CMP (id, name) values (184, 'Alfuzosin Hydrochloride');
insert into DELIVERY_CMP (id, name) values (185, 'ANEW');
insert into DELIVERY_CMP (id, name) values (186, 'Omnicide Antimicrobial');
insert into DELIVERY_CMP (id, name) values (187, 'Axe');
insert into DELIVERY_CMP (id, name) values (188, 'Warfarin Sodium');
insert into DELIVERY_CMP (id, name) values (189, 'Allopurinol');
insert into DELIVERY_CMP (id, name) values (190, 'ATORVASTATIN CALCIUM');
insert into DELIVERY_CMP (id, name) values (191, 'Rizatriptan Benzoate');
insert into DELIVERY_CMP (id, name) values (192, 'Gabapentin');
insert into DELIVERY_CMP (id, name) values (193, 'Colgate Junior Bubble Fruit');
insert into DELIVERY_CMP (id, name) values (194, 'Gabapentin');
insert into DELIVERY_CMP (id, name) values (195, 'Verapamil Hydrochloride');
insert into DELIVERY_CMP (id, name) values (196, 'Hickory/Pecan Mixture');
insert into DELIVERY_CMP (id, name) values (197, 'Food - Plant Source, Soybean Glycine soja');
insert into DELIVERY_CMP (id, name) values (198, 'Propranolol Hydrochloride');
insert into DELIVERY_CMP (id, name) values (199, 'Turkey');
insert into DELIVERY_CMP (id, name) values (200, 'VEHICLE BOAT BAG MEDICAL');
insert into DELIVERY_CMP (id, name) values (201, 'Nuvel Softy Antiperspirant Deodorant Stick');
insert into DELIVERY_CMP (id, name) values (202, 'Toppik Womens Hair Regrowth Treatment');
insert into DELIVERY_CMP (id, name) values (203, 'Australian Gold');
insert into DELIVERY_CMP (id, name) values (204, 'Flawless Finish Bare Perfection Makeup SPF 8 Ivory');
insert into DELIVERY_CMP (id, name) values (205, 'Zetia');
insert into DELIVERY_CMP (id, name) values (206, 'Instant Hand Sanitizer');
insert into DELIVERY_CMP (id, name) values (207, 'Labetalol HCl');
insert into DELIVERY_CMP (id, name) values (208, 'OXYCONTIN');
insert into DELIVERY_CMP (id, name) values (209, 'Captopril');
insert into DELIVERY_CMP (id, name) values (210, 'KETOROLAC TROMETHAMINE');
insert into DELIVERY_CMP (id, name) values (211, 'Metoclopramide');
insert into DELIVERY_CMP (id, name) values (212, 'Demadex');
insert into DELIVERY_CMP (id, name) values (213, 'Gemfibrozil');
insert into DELIVERY_CMP (id, name) values (214, 'Ibuprofen');
insert into DELIVERY_CMP (id, name) values (215, 'METFORMIN HYDROCHLORIDE');
insert into DELIVERY_CMP (id, name) values (216, 'WALGREENS COOL AND HEAT MUSCLE AND JOINT RELIEF');
insert into DELIVERY_CMP (id, name) values (217, 'Zicam');
insert into DELIVERY_CMP (id, name) values (218, 'Alendronate Sodium');
insert into DELIVERY_CMP (id, name) values (219, 'Methylin');
insert into DELIVERY_CMP (id, name) values (220, 'Phytonadione');
insert into DELIVERY_CMP (id, name) values (221, 'FusionBeauty Colorceuticals PrimeResults Tinted Moisturizer SPF15 Ivory');
insert into DELIVERY_CMP (id, name) values (222, 'Levothyroxine Sodium');
insert into DELIVERY_CMP (id, name) values (223, 'Metoprolol Tartrate and Hydrochlorothiazide');
insert into DELIVERY_CMP (id, name) values (224, 'Methotrexate');
insert into DELIVERY_CMP (id, name) values (225, 'DRAXIMAGE MAA');
insert into DELIVERY_CMP (id, name) values (226, 'TC EnrichedFoam');
insert into DELIVERY_CMP (id, name) values (227, 'Childrens Ibuprofen');
insert into DELIVERY_CMP (id, name) values (228, 'Nefazodone Hydrochloride');
insert into DELIVERY_CMP (id, name) values (229, 'UV Capture Vita Sun Gel');
insert into DELIVERY_CMP (id, name) values (230, 'ProcureTriple Antibiotic');
insert into DELIVERY_CMP (id, name) values (231, 'Nitrogen');
insert into DELIVERY_CMP (id, name) values (232, 'Sinus and Allergy PE');
insert into DELIVERY_CMP (id, name) values (233, 'Metronidazole');
insert into DELIVERY_CMP (id, name) values (234, 'Amlodipine besylate and Atorvastatin calcium');
insert into DELIVERY_CMP (id, name) values (235, 'GIVEN BY NATURE OLIVE MASK SHEET');
insert into DELIVERY_CMP (id, name) values (236, 'Pepper Tree Pollen');
insert into DELIVERY_CMP (id, name) values (237, 'Mi-Omega NF');
insert into DELIVERY_CMP (id, name) values (238, 'Pacnex');
insert into DELIVERY_CMP (id, name) values (239, 'naproxen sodium');
insert into DELIVERY_CMP (id, name) values (240, 'Pulsatilla Tormentilla');
insert into DELIVERY_CMP (id, name) values (241, 'Artificial Tears');
insert into DELIVERY_CMP (id, name) values (242, 'PVP Prep');
insert into DELIVERY_CMP (id, name) values (243, 'PROPECIA');
insert into DELIVERY_CMP (id, name) values (244, 'pharMAX rebuild');
insert into DELIVERY_CMP (id, name) values (245, 'Methylphenidate Hydrochloride');
insert into DELIVERY_CMP (id, name) values (246, 'Oral hCG Activator');
insert into DELIVERY_CMP (id, name) values (247, 'Isosorbide Dinitrate');
insert into DELIVERY_CMP (id, name) values (248, 'HAY FEVER 1');
insert into DELIVERY_CMP (id, name) values (249, 'FRAXINUS AMERICANA POLLEN');
insert into DELIVERY_CMP (id, name) values (250, 'Bellagio Sunscreen SPF 15');
insert into DELIVERY_CMP (id, name) values (251, 'ESZOPICLONE');
insert into DELIVERY_CMP (id, name) values (252, 'CitraNatal Rx');
insert into DELIVERY_CMP (id, name) values (253, 'Amoxicillin and Clavulanate Potassium');
insert into DELIVERY_CMP (id, name) values (254, 'Tinted BB');
insert into DELIVERY_CMP (id, name) values (255, 'rx act ibuprofen pm');
insert into DELIVERY_CMP (id, name) values (256, 'PLAGENTRA BABY SUNCITY');
insert into DELIVERY_CMP (id, name) values (257, 'alfentanil hydrochloride');
insert into DELIVERY_CMP (id, name) values (258, 'Aspirin');
insert into DELIVERY_CMP (id, name) values (259, 'Family Wellness Sensitive Extra Whitening');
insert into DELIVERY_CMP (id, name) values (260, 'Pfizerpen');
insert into DELIVERY_CMP (id, name) values (261, 'Pain Relief Cold');
insert into DELIVERY_CMP (id, name) values (262, 'Metoprolol Succinate');
insert into DELIVERY_CMP (id, name) values (263, 'Glipizide');
insert into DELIVERY_CMP (id, name) values (264, 'Anti-Bacterial Hand');
insert into DELIVERY_CMP (id, name) values (265, 'EPICOCCUM NIGRUM');
insert into DELIVERY_CMP (id, name) values (266, 'Trepoxicam-7.5');
insert into DELIVERY_CMP (id, name) values (267, 'Oxycodone Hydrochloride');
insert into DELIVERY_CMP (id, name) values (268, 'Listerine Healthy White Anticavity Mouthrinse Gentle Clean Mint');
insert into DELIVERY_CMP (id, name) values (269, 'TOPIRAMATE');
insert into DELIVERY_CMP (id, name) values (270, 'Doxazosin');
insert into DELIVERY_CMP (id, name) values (271, 'Ketorolac Tromethamine');
insert into DELIVERY_CMP (id, name) values (272, 'Healing');
insert into DELIVERY_CMP (id, name) values (273, 'Antacid Antigas');
insert into DELIVERY_CMP (id, name) values (274, 'Teething Irritability');
insert into DELIVERY_CMP (id, name) values (275, 'Nicorette');
insert into DELIVERY_CMP (id, name) values (276, 'Melatonin');
insert into DELIVERY_CMP (id, name) values (277, 'Gentamicin');
insert into DELIVERY_CMP (id, name) values (278, 'benzonatate');
insert into DELIVERY_CMP (id, name) values (279, 'Pfizerpen');
insert into DELIVERY_CMP (id, name) values (280, 'Oxycodone Hydrochloride');
insert into DELIVERY_CMP (id, name) values (281, 'PMS Tone');
insert into DELIVERY_CMP (id, name) values (282, 'equate aspirin');
insert into DELIVERY_CMP (id, name) values (283, 'Lamotrigine');
insert into DELIVERY_CMP (id, name) values (284, 'fexofenadine hydrochloride');
insert into DELIVERY_CMP (id, name) values (285, 'Doxazosin');
insert into DELIVERY_CMP (id, name) values (286, 'Estradiol Transdermal System');
insert into DELIVERY_CMP (id, name) values (287, 'SPF 30 Sunscreen');
insert into DELIVERY_CMP (id, name) values (288, 'Ultramicrosize Griseofulvin');
insert into DELIVERY_CMP (id, name) values (289, 'Clearasil');
insert into DELIVERY_CMP (id, name) values (290, 'ALOE UP PRO 50');
insert into DELIVERY_CMP (id, name) values (291, 'ETHYL ALCOHOL');
insert into DELIVERY_CMP (id, name) values (292, 'Methylergonovine Maleate');
insert into DELIVERY_CMP (id, name) values (293, 'Cardizem LA');
insert into DELIVERY_CMP (id, name) values (294, 'Standardized Mite, Dermatophagoides farinae');
insert into DELIVERY_CMP (id, name) values (295, 'Quetiapine Fumarate');
insert into DELIVERY_CMP (id, name) values (296, 'Stool Softener');
insert into DELIVERY_CMP (id, name) values (297, 'ONGLYZA');
insert into DELIVERY_CMP (id, name) values (298, 'Lorazepam');
insert into DELIVERY_CMP (id, name) values (299, 'Vancomycin Hydrochloride');
insert into DELIVERY_CMP (id, name) values (300, 'Sinus-Tone');
insert into DELIVERY_CMP (id, name) values (301, 'Amiloride Hydrochloride');
insert into DELIVERY_CMP (id, name) values (302, 'Dove');
insert into DELIVERY_CMP (id, name) values (303, 'Tolmetin Sodium');
insert into DELIVERY_CMP (id, name) values (304, 'Publix Burn Relief');
insert into DELIVERY_CMP (id, name) values (305, 'Baclofen');
insert into DELIVERY_CMP (id, name) values (306, 'Lady Speed INVISIBLE DRY antiperspirant deodorant');
insert into DELIVERY_CMP (id, name) values (307, 'Topcare ibuprofen');
insert into DELIVERY_CMP (id, name) values (308, 'Glimepiride');
insert into DELIVERY_CMP (id, name) values (309, '6 CREME 410 TEINTEE');
insert into DELIVERY_CMP (id, name) values (310, 'Xolox');
insert into DELIVERY_CMP (id, name) values (311, 'correcting cream Broad Spectrum SPF 15');
insert into DELIVERY_CMP (id, name) values (312, 'Ketodan');
insert into DELIVERY_CMP (id, name) values (313, 'Meloxicam');
insert into DELIVERY_CMP (id, name) values (314, 'Biofreeze Roll-On');
insert into DELIVERY_CMP (id, name) values (315, 'Acetadryl');
insert into DELIVERY_CMP (id, name) values (316, 'ProFormance Series Foam Alcohol Hand Sanitizer');
insert into DELIVERY_CMP (id, name) values (317, 'SEAWEED MEDICLEAR MASK');
insert into DELIVERY_CMP (id, name) values (318, 'PAIN GOODBYE AQUEOUS PATCH');
insert into DELIVERY_CMP (id, name) values (319, 'THIAMINE HYDROCHLORIDE');
insert into DELIVERY_CMP (id, name) values (320, 'Nexiclon XR');
insert into DELIVERY_CMP (id, name) values (321, 'Tretin-X');
insert into DELIVERY_CMP (id, name) values (322, 'Wormwood');
insert into DELIVERY_CMP (id, name) values (323, 'Contac Cold and Flu');
insert into DELIVERY_CMP (id, name) values (324, 'BZK ANTISEPTIC TOWELETTE');
insert into DELIVERY_CMP (id, name) values (325, 'LABORATOIRE REMEDE TRANSLUCENT UV COAT TINT 3');
insert into DELIVERY_CMP (id, name) values (326, 'HAWAIIAN Tropic Dry Clear Sunscreen Broad Spectrum SPF 12 water resistant');
insert into DELIVERY_CMP (id, name) values (327, 'Modafinil');
insert into DELIVERY_CMP (id, name) values (328, 'Minocycline Hydrochloride');
insert into DELIVERY_CMP (id, name) values (329, 'eszopiclone');
insert into DELIVERY_CMP (id, name) values (330, 'ACYCLOVIR');
insert into DELIVERY_CMP (id, name) values (331, 'Gabapentin');
insert into DELIVERY_CMP (id, name) values (332, 'Laura Mercier Foundation Primer Protect');
insert into DELIVERY_CMP (id, name) values (333, 'Mountain Cedar Pollen');
insert into DELIVERY_CMP (id, name) values (334, 'EXSEL SPORT');
insert into DELIVERY_CMP (id, name) values (335, 'Fluocinolone Acetonide');
insert into DELIVERY_CMP (id, name) values (336, 'OLEA EUROPAEA POLLEN');
insert into DELIVERY_CMP (id, name) values (337, 'AZITHROMYCIN');
insert into DELIVERY_CMP (id, name) values (338, 'Good Neighbor Pharmacy Childrens Pain and Fever');
insert into DELIVERY_CMP (id, name) values (339, 'LEVAQUIN');
insert into DELIVERY_CMP (id, name) values (340, 'SunDrops 77');
insert into DELIVERY_CMP (id, name) values (341, 'Triamcinolone Acetonide');
insert into DELIVERY_CMP (id, name) values (342, 'Tinidazole');
insert into DELIVERY_CMP (id, name) values (343, 'Morphine Sulfate');
insert into DELIVERY_CMP (id, name) values (344, 'Clonidine Hydrochloride');
insert into DELIVERY_CMP (id, name) values (345, 'Labetalol HCl');
insert into DELIVERY_CMP (id, name) values (346, 'Yellow Hornet hymenoptera venom Venomil Maintenance');
insert into DELIVERY_CMP (id, name) values (347, 'Hope In A Tinted Moisturizer');
insert into DELIVERY_CMP (id, name) values (348, 'Smith and Johnson Antibacterial');
insert into DELIVERY_CMP (id, name) values (349, 'Short Ragweed Pollen');
insert into DELIVERY_CMP (id, name) values (350, 'GUNA-TF HERPES');
insert into DELIVERY_CMP (id, name) values (351, 'Jay-Phyl');
insert into DELIVERY_CMP (id, name) values (352, 'ZAFIRLUKAST');
insert into DELIVERY_CMP (id, name) values (353, 'extra strength');
insert into DELIVERY_CMP (id, name) values (354, 'Lamotrigine');
insert into DELIVERY_CMP (id, name) values (355, 'Atenolol');
insert into DELIVERY_CMP (id, name) values (356, 'Lotrel');
insert into DELIVERY_CMP (id, name) values (357, 'Milrinone Lactate');
insert into DELIVERY_CMP (id, name) values (358, 'Prednisone');
insert into DELIVERY_CMP (id, name) values (359, 'Phosphorus 6');
insert into DELIVERY_CMP (id, name) values (360, 'Lorazepam');
insert into DELIVERY_CMP (id, name) values (361, 'TENEX');
insert into DELIVERY_CMP (id, name) values (362, 'Night time multi symptom cold/flu relief');
insert into DELIVERY_CMP (id, name) values (363, 'Extra Strength Pain Reliever PM');
insert into DELIVERY_CMP (id, name) values (364, 'Diltiazem Hydrochloride');
insert into DELIVERY_CMP (id, name) values (365, 'Myobloc');
insert into DELIVERY_CMP (id, name) values (366, 'Fluocinonide');
insert into DELIVERY_CMP (id, name) values (367, 'Amidate');
insert into DELIVERY_CMP (id, name) values (368, 'ARNICAID');
insert into DELIVERY_CMP (id, name) values (369, 'Black Locust');
insert into DELIVERY_CMP (id, name) values (370, 'Rivastigmine Tartrate');
insert into DELIVERY_CMP (id, name) values (371, 'MANGO BEBE LIP CARE');
insert into DELIVERY_CMP (id, name) values (372, 'Christian Dior Prestige Brightening Revitalizing UV Base SPF 50');
insert into DELIVERY_CMP (id, name) values (373, 'Quetiapine fumarate');
insert into DELIVERY_CMP (id, name) values (374, 'SPF 20 UVA/UVB');
insert into DELIVERY_CMP (id, name) values (375, 'Ergocalciferol');
insert into DELIVERY_CMP (id, name) values (376, 'Mini Berry Lip Balm Cherry');
insert into DELIVERY_CMP (id, name) values (377, 'Varibar Honey');
insert into DELIVERY_CMP (id, name) values (378, 'Gallbladder Dr.');
insert into DELIVERY_CMP (id, name) values (379, 'Mucinex DM');
insert into DELIVERY_CMP (id, name) values (380, 'benefit BIG EASY BROAD SPECTRUM SPF 35 SUNSCREEN multi-balancing complexion perfector - 04 MEDIUM');
insert into DELIVERY_CMP (id, name) values (381, 'Anit-Inflammatory');
insert into DELIVERY_CMP (id, name) values (382, 'Oto End 10');
insert into DELIVERY_CMP (id, name) values (383, 'Severe Oral Pain Reliever');
insert into DELIVERY_CMP (id, name) values (384, 'nasal');
insert into DELIVERY_CMP (id, name) values (385, 'Famotidine');
insert into DELIVERY_CMP (id, name) values (386, 'BIO-RYTUSS');
insert into DELIVERY_CMP (id, name) values (387, 'Fycompa');
insert into DELIVERY_CMP (id, name) values (388, 'Nateglinide');
insert into DELIVERY_CMP (id, name) values (389, 'Nalbuphine Hydrochloride');
insert into DELIVERY_CMP (id, name) values (390, 'Renes Mesenchyme');
insert into DELIVERY_CMP (id, name) values (391, 'Anal Itch Assist');
insert into DELIVERY_CMP (id, name) values (392, 'Alfuzosin Hydrochloride');
insert into DELIVERY_CMP (id, name) values (393, 'LAMICTAL');
insert into DELIVERY_CMP (id, name) values (394, 'bacitracin zinc, neomycin sulfate and polymyxin b sulfate');
insert into DELIVERY_CMP (id, name) values (395, 'Multi-Symptom Cold Flu and Sore Throat');
insert into DELIVERY_CMP (id, name) values (396, 'Metronidazole');
insert into DELIVERY_CMP (id, name) values (397, 'Capture Totale Radiance Restoring Serum Foundation SPF 15 040');
insert into DELIVERY_CMP (id, name) values (398, 'Haloperidol');
insert into DELIVERY_CMP (id, name) values (399, 'Lidocaine Hydrochloride');
insert into DELIVERY_CMP (id, name) values (400, 'X-Out Wash-In Treatment');
insert into DELIVERY_CMP (id, name) values (401, 'Bikini Zone MEDICATED After Shave Fresh Scent');
insert into DELIVERY_CMP (id, name) values (402, 'Technetium Tc99m Generator');
insert into DELIVERY_CMP (id, name) values (403, 'Witch Hazel');
insert into DELIVERY_CMP (id, name) values (404, 'fenofibrate');
insert into DELIVERY_CMP (id, name) values (405, 'Perfect Purity Advanced Hand Sanitizer Refreshing');
insert into DELIVERY_CMP (id, name) values (406, 'Lovastatin');
insert into DELIVERY_CMP (id, name) values (407, 'Gleostine');
insert into DELIVERY_CMP (id, name) values (408, 'Carelessweed');
insert into DELIVERY_CMP (id, name) values (409, 'SHISEIDO SHEER AND PERFECT FOUNDATION');
insert into DELIVERY_CMP (id, name) values (410, 'Black Olive');
insert into DELIVERY_CMP (id, name) values (411, 'Prednisone');
insert into DELIVERY_CMP (id, name) values (412, 'RIFAMPIN');
insert into DELIVERY_CMP (id, name) values (413, 'THERA Moisturizing Body Shield');
insert into DELIVERY_CMP (id, name) values (414, 'Beautipharm All Day Moisturizing Balm');
insert into DELIVERY_CMP (id, name) values (415, 'Trihexyphenidyl Hydrochloride');
insert into DELIVERY_CMP (id, name) values (416, 'Actoplus Met');
insert into DELIVERY_CMP (id, name) values (417, 'OXYGEN');
insert into DELIVERY_CMP (id, name) values (418, 'Cystografin');
insert into DELIVERY_CMP (id, name) values (419, 'Oxygen');
insert into DELIVERY_CMP (id, name) values (420, 'NAPROXEN');
insert into DELIVERY_CMP (id, name) values (421, 'ALPRAZOLAM');
insert into DELIVERY_CMP (id, name) values (422, 'Terapie Callus Remover');
insert into DELIVERY_CMP (id, name) values (423, 'Miconazole nitrate');
insert into DELIVERY_CMP (id, name) values (424, 'Lisinopril');
insert into DELIVERY_CMP (id, name) values (425, 'Tamsulosin hydrochloride');
insert into DELIVERY_CMP (id, name) values (426, 'Ibuprofen');
insert into DELIVERY_CMP (id, name) values (427, 'Conjunct-a-Clear');
insert into DELIVERY_CMP (id, name) values (428, 'DEPRESSION COMPOSITION');
insert into DELIVERY_CMP (id, name) values (429, 'calcium antacid');
insert into DELIVERY_CMP (id, name) values (430, 'Bio Larch');
insert into DELIVERY_CMP (id, name) values (431, 'Diflucan');
insert into DELIVERY_CMP (id, name) values (432, 'POPULUS DELTOIDES SSP MONILIFERA POLLEN');
insert into DELIVERY_CMP (id, name) values (433, 'Stool Softener');
insert into DELIVERY_CMP (id, name) values (434, 'Terrasil Itch, Rash and Pain Relief');
insert into DELIVERY_CMP (id, name) values (435, 'Gelato APF');
insert into DELIVERY_CMP (id, name) values (436, 'Fluconazole');
insert into DELIVERY_CMP (id, name) values (437, 'Australian Gold');
insert into DELIVERY_CMP (id, name) values (438, 'SWEET CLOVER POLLEN');
insert into DELIVERY_CMP (id, name) values (439, 'Intervene Makeup SPF 15 Soft Beige');
insert into DELIVERY_CMP (id, name) values (440, 'Bupropion Hydrochloride');
insert into DELIVERY_CMP (id, name) values (441, 'No7 Beautifully Matte Foundation Sunscreen Broad Spectrum SPF 15 Wheat');
insert into DELIVERY_CMP (id, name) values (442, 'BANANA BOAT');
insert into DELIVERY_CMP (id, name) values (443, 'Losartan Potassium');
insert into DELIVERY_CMP (id, name) values (444, 'Ili Hand Sanitizer');
insert into DELIVERY_CMP (id, name) values (445, 'allergy and congestion relief');
insert into DELIVERY_CMP (id, name) values (446, 'Metoprolol Succinate');
insert into DELIVERY_CMP (id, name) values (447, 'Multi-Vitamin');
insert into DELIVERY_CMP (id, name) values (448, 'Chlordiazepoxide Hydrochloride');
insert into DELIVERY_CMP (id, name) values (449, 'Allergies Food Chemicals');
insert into DELIVERY_CMP (id, name) values (450, 'Risperidone');
insert into DELIVERY_CMP (id, name) values (451, 'FML FORTE');
insert into DELIVERY_CMP (id, name) values (452, 'Atenolol');
insert into DELIVERY_CMP (id, name) values (453, 'BUPROPION HYDROCHLORIDE');
insert into DELIVERY_CMP (id, name) values (454, 'OXYGEN');
insert into DELIVERY_CMP (id, name) values (455, 'Albuterol Sulfate');
insert into DELIVERY_CMP (id, name) values (456, 'Skin Irritation');
insert into DELIVERY_CMP (id, name) values (457, 'Renaforce');
insert into DELIVERY_CMP (id, name) values (458, 'Midazolam HCl');
insert into DELIVERY_CMP (id, name) values (459, 'NP Thyroid 90');
insert into DELIVERY_CMP (id, name) values (460, 'Pasta de Lassar Andromaco');
insert into DELIVERY_CMP (id, name) values (461, 'Libido');
insert into DELIVERY_CMP (id, name) values (462, 'Extra Strength Acetaminophen');
insert into DELIVERY_CMP (id, name) values (463, 'Nephron FA');
insert into DELIVERY_CMP (id, name) values (464, 'Pramipexole Dihydrochloride');
insert into DELIVERY_CMP (id, name) values (465, 'Soft Care Hand Sanitizer');
insert into DELIVERY_CMP (id, name) values (466, 'Smart Sense Hydrocortisone');
insert into DELIVERY_CMP (id, name) values (467, 'Gas Relief');
insert into DELIVERY_CMP (id, name) values (468, 'Divalproex Sodium');
insert into DELIVERY_CMP (id, name) values (469, 'Treatment Set TS348651');
insert into DELIVERY_CMP (id, name) values (470, 'BLATELLA GERMANICA');
insert into DELIVERY_CMP (id, name) values (471, 'mally Lip Defender');
insert into DELIVERY_CMP (id, name) values (472, 'Hydralazine Hydrochloride');
insert into DELIVERY_CMP (id, name) values (473, 'PINEAPPLE');
insert into DELIVERY_CMP (id, name) values (474, 'Treatment Set TS336682');
insert into DELIVERY_CMP (id, name) values (475, 'Premarin');
insert into DELIVERY_CMP (id, name) values (476, 'Smart Sense Allergy and Congestion Relief-D');
insert into DELIVERY_CMP (id, name) values (477, 'Pioglitazone Hydrochloride');
insert into DELIVERY_CMP (id, name) values (478, 'Allergy Relief D');
insert into DELIVERY_CMP (id, name) values (479, 'WHITE ASH POLLEN');
insert into DELIVERY_CMP (id, name) values (480, 'Deb Med Antimicrobial Foaming Hand Wash Fresh Grapefruit');
insert into DELIVERY_CMP (id, name) values (481, 'CARBO VEGETABILIS');
insert into DELIVERY_CMP (id, name) values (482, 'Lisinopril');
insert into DELIVERY_CMP (id, name) values (483, 'antacid');
insert into DELIVERY_CMP (id, name) values (484, 'Metformin Hydrochloride');
insert into DELIVERY_CMP (id, name) values (485, 'Alcohol');
insert into DELIVERY_CMP (id, name) values (486, 'Infection');
insert into DELIVERY_CMP (id, name) values (487, 'Sodium Bicarbonate');
insert into DELIVERY_CMP (id, name) values (488, 'Acyclovir');
insert into DELIVERY_CMP (id, name) values (489, 'Nifedipine');
insert into DELIVERY_CMP (id, name) values (490, 'Lisinopril 5mg');
insert into DELIVERY_CMP (id, name) values (491, 'psorcon');
insert into DELIVERY_CMP (id, name) values (492, 'Vital Fluid IV Nano Gold Serum');
insert into DELIVERY_CMP (id, name) values (493, 'Loratadine');
insert into DELIVERY_CMP (id, name) values (494, 'Sulfamethoxazole and Trimethoprim');
insert into DELIVERY_CMP (id, name) values (495, 'acid reducer 150');
insert into DELIVERY_CMP (id, name) values (496, 'Clarithromycin');
insert into DELIVERY_CMP (id, name) values (497, 'Prednisolone Sodium Phosphate');
insert into DELIVERY_CMP (id, name) values (498, 'Privet Pollen');
insert into DELIVERY_CMP (id, name) values (499, 'KINERASE');
insert into DELIVERY_CMP (id, name) values (500, 'In-111 DTPA');
insert into DELIVERY_CMP (id, name) values (501, 'Glipizide');
insert into DELIVERY_CMP (id, name) values (502, 'Genuine Hand Sanitizer');
insert into DELIVERY_CMP (id, name) values (503, 'Topiramate');
insert into DELIVERY_CMP (id, name) values (504, 'Isoniazid');
insert into DELIVERY_CMP (id, name) values (505, 'UltrasolSunscreen');
insert into DELIVERY_CMP (id, name) values (506, 'Naphazoline HCI And Pheniramine Maleate');
insert into DELIVERY_CMP (id, name) values (507, 'Oxycodone Hydrochloride');
insert into DELIVERY_CMP (id, name) values (508, 'Clarity Clear Skin Essentials');
insert into DELIVERY_CMP (id, name) values (509, 'Aplicare Povidone-Iodine');
insert into DELIVERY_CMP (id, name) values (510, 'SUPERDEFENSE AGE DEFENSE BROAD SPECTRUM SPF 20');
insert into DELIVERY_CMP (id, name) values (511, 'AHC Vital C Complex Mask');
insert into DELIVERY_CMP (id, name) values (512, 'EQUATE');
insert into DELIVERY_CMP (id, name) values (513, 'ZOLPIDEM TARTRATE');
insert into DELIVERY_CMP (id, name) values (514, 'Tangerin Whitening Hand');
insert into DELIVERY_CMP (id, name) values (515, 'GM Collin Mineral Sun Veil');
insert into DELIVERY_CMP (id, name) values (516, 'Loperamide Hydrochloride');
insert into DELIVERY_CMP (id, name) values (517, 'UltraMax Invisible Solid');
insert into DELIVERY_CMP (id, name) values (518, 'Phendimetrazine Tartrate');
insert into DELIVERY_CMP (id, name) values (519, 'APIS MELLIFICA');
insert into DELIVERY_CMP (id, name) values (520, 'Aspirin');
insert into DELIVERY_CMP (id, name) values (521, 'Phenytoin Sodium');
insert into DELIVERY_CMP (id, name) values (522, 'Theraproxen-90');
insert into DELIVERY_CMP (id, name) values (523, 'childrens acetaminophen');
insert into DELIVERY_CMP (id, name) values (524, 'Leeks');
insert into DELIVERY_CMP (id, name) values (525, 'Bacitracin Zinc');
insert into DELIVERY_CMP (id, name) values (526, 'Chest Congestion');
insert into DELIVERY_CMP (id, name) values (527, 'Antacid');
insert into DELIVERY_CMP (id, name) values (528, 'Small Cuts and Burns');
insert into DELIVERY_CMP (id, name) values (529, 'DG BODY');
insert into DELIVERY_CMP (id, name) values (530, 'Cardioforce');
insert into DELIVERY_CMP (id, name) values (531, 'the Balm BalmShelter tinted moisturizer SPF 18 broad spectrum after dark');
insert into DELIVERY_CMP (id, name) values (532, 'Epsom Salt');
insert into DELIVERY_CMP (id, name) values (533, 'Zoloft');
insert into DELIVERY_CMP (id, name) values (534, 'Spironolactone');
insert into DELIVERY_CMP (id, name) values (535, 'Antibacterial Hand Sanitizer');
insert into DELIVERY_CMP (id, name) values (536, 'Triamcinolone Acetonide');
insert into DELIVERY_CMP (id, name) values (537, 'Bumetanide');
insert into DELIVERY_CMP (id, name) values (538, 'Good Neighbor Pharmacy');
insert into DELIVERY_CMP (id, name) values (539, 'Cisplatin');
insert into DELIVERY_CMP (id, name) values (540, 'Isomers Clear Skin Acne Treatment Lotion');
insert into DELIVERY_CMP (id, name) values (541, 'TYVASO');
insert into DELIVERY_CMP (id, name) values (542, 'Hydromorphone HCl');
insert into DELIVERY_CMP (id, name) values (543, 'Oxytocin');
insert into DELIVERY_CMP (id, name) values (544, 'LAMISL AF');
insert into DELIVERY_CMP (id, name) values (545, 'Youduo Gentle Whitening Fluoride');
insert into DELIVERY_CMP (id, name) values (546, 'Phentermine Hydrochloride');
insert into DELIVERY_CMP (id, name) values (547, 'Modafinil');
insert into DELIVERY_CMP (id, name) values (548, 'BioTPres');
insert into DELIVERY_CMP (id, name) values (549, 'HAWAIIAN TROPIC');
insert into DELIVERY_CMP (id, name) values (550, 'Robinia Nicotiana');
insert into DELIVERY_CMP (id, name) values (551, 'Amlodipine besylate and Atorvastatin calcium');
insert into DELIVERY_CMP (id, name) values (552, 'Dove');
insert into DELIVERY_CMP (id, name) values (553, 'Oxygen');
insert into DELIVERY_CMP (id, name) values (554, 'Anticavity');
insert into DELIVERY_CMP (id, name) values (555, 'Trelstar');
insert into DELIVERY_CMP (id, name) values (556, 'Naproxen');
insert into DELIVERY_CMP (id, name) values (557, 'BANANA BOAT');
insert into DELIVERY_CMP (id, name) values (558, 'Ultra-TechneKow');
insert into DELIVERY_CMP (id, name) values (559, 'Ropinirole Hydrochloride');
insert into DELIVERY_CMP (id, name) values (560, 'Tartar control plus');
insert into DELIVERY_CMP (id, name) values (561, 'Pseudoephedrine hydrochloride');
insert into DELIVERY_CMP (id, name) values (562, 'Demadex');
insert into DELIVERY_CMP (id, name) values (563, 'Minocycline Hydrochloride');
insert into DELIVERY_CMP (id, name) values (564, 'Digoxin');
insert into DELIVERY_CMP (id, name) values (565, 'DR. RECKEWEG R34 Calcossin');
insert into DELIVERY_CMP (id, name) values (566, 'LBEL FILLING EFFECT FOUNDATION SPF 10');
insert into DELIVERY_CMP (id, name) values (567, 'Lisinopril');
insert into DELIVERY_CMP (id, name) values (568, 'IBUPROFEN');
insert into DELIVERY_CMP (id, name) values (569, 'Green Guard Cough Drop Relief');
insert into DELIVERY_CMP (id, name) values (570, 'Divalproex Sodium');
insert into DELIVERY_CMP (id, name) values (571, 'BENADRYL Extra Strength Itch Cooling');
insert into DELIVERY_CMP (id, name) values (572, 'SEROQUEL');
insert into DELIVERY_CMP (id, name) values (573, 'Darkleaves Mugwort');
insert into DELIVERY_CMP (id, name) values (574, 'DR RECKEWEG BC-1');
insert into DELIVERY_CMP (id, name) values (575, 'Unithroid');
insert into DELIVERY_CMP (id, name) values (576, 'REPARA');
insert into DELIVERY_CMP (id, name) values (577, 'Flucelvax');
insert into DELIVERY_CMP (id, name) values (578, 'Amlodipine and Atorvastatin');
insert into DELIVERY_CMP (id, name) values (579, 'Oxygen');
insert into DELIVERY_CMP (id, name) values (580, 'Bupropion Hydrochloride');
insert into DELIVERY_CMP (id, name) values (581, 'Acyclovir');
insert into DELIVERY_CMP (id, name) values (582, 'Cefoxitin');
insert into DELIVERY_CMP (id, name) values (583, 'BOA VIDA Cleansing');
insert into DELIVERY_CMP (id, name) values (584, 'Duravent DM');
insert into DELIVERY_CMP (id, name) values (585, 'Bioelements');
insert into DELIVERY_CMP (id, name) values (586, 'dg health naproxen sodium');
insert into DELIVERY_CMP (id, name) values (587, 'Accident - Injury Rescue');
insert into DELIVERY_CMP (id, name) values (588, 'Senna');
insert into DELIVERY_CMP (id, name) values (589, 'PAROXETINE');
insert into DELIVERY_CMP (id, name) values (590, 'Nighttime Sleep Aid');
insert into DELIVERY_CMP (id, name) values (591, 'FROVA');
insert into DELIVERY_CMP (id, name) values (592, 'No7 Lifting and Firming Foundation Sunscreen SPF 15 Walnut');
insert into DELIVERY_CMP (id, name) values (593, 'ERYTHROMYCIN Base Filmtab');
insert into DELIVERY_CMP (id, name) values (594, 'Jantoven');
insert into DELIVERY_CMP (id, name) values (595, 'Tretinoin');
insert into DELIVERY_CMP (id, name) values (596, 'Skin So Soft Bug Guard Plus IR3535');
insert into DELIVERY_CMP (id, name) values (597, 'Metoprolol Succinate');
insert into DELIVERY_CMP (id, name) values (598, 'Nateglinide');
insert into DELIVERY_CMP (id, name) values (599, 'Sumatriptan Succinate');
insert into DELIVERY_CMP (id, name) values (600, 'Venlafaxine Hydrochloride');
insert into DELIVERY_CMP (id, name) values (601, 'NITROGEN');
insert into DELIVERY_CMP (id, name) values (602, 'Nitrogen');
insert into DELIVERY_CMP (id, name) values (603, 'REMEDY Calazime Skin Protectant');
insert into DELIVERY_CMP (id, name) values (604, 'Sugar Cookies Scented Antibacterial Hand Sanitizer');
insert into DELIVERY_CMP (id, name) values (605, 'LANEIGE SunScreen Triple');
insert into DELIVERY_CMP (id, name) values (606, 'RHODOTORULA RUBRA');
insert into DELIVERY_CMP (id, name) values (607, 'ULMUS CRASSIFOLIA POLLEN');
insert into DELIVERY_CMP (id, name) values (608, 'Metoclopramide');
insert into DELIVERY_CMP (id, name) values (609, 'Aspirin');
insert into DELIVERY_CMP (id, name) values (610, 'Annual Blue Grass');
insert into DELIVERY_CMP (id, name) values (611, 'OXYGEN');
insert into DELIVERY_CMP (id, name) values (612, 'Eszopiclone');
insert into DELIVERY_CMP (id, name) values (613, 'Prostate Symptom Relief');
insert into DELIVERY_CMP (id, name) values (614, 'Tula Tantrum Tamer');
insert into DELIVERY_CMP (id, name) values (615, 'venlafaxine hydrochloride');
insert into DELIVERY_CMP (id, name) values (616, 'Prednisone');
insert into DELIVERY_CMP (id, name) values (617, 'SANIFOAM HAND SANITIZER');
insert into DELIVERY_CMP (id, name) values (618, 'Dermablend Cover');
insert into DELIVERY_CMP (id, name) values (619, 'Health and Beyond Antiseptic Hand Sanitizer');
insert into DELIVERY_CMP (id, name) values (620, 'Dexmethylphenidate hydrochloride');
insert into DELIVERY_CMP (id, name) values (621, 'napoleon PERDIS FOUNDATION STICK BROAD SPECTRUM SPF 15 Look 4');
insert into DELIVERY_CMP (id, name) values (622, 'Gabapentin');
insert into DELIVERY_CMP (id, name) values (623, 'Lorazepam');
insert into DELIVERY_CMP (id, name) values (624, 'ShopRite Adult Tussin');
insert into DELIVERY_CMP (id, name) values (625, 'Yeastrol');
insert into DELIVERY_CMP (id, name) values (626, 'Simvastatin');
insert into DELIVERY_CMP (id, name) values (627, 'Old Spice High Endurance');
insert into DELIVERY_CMP (id, name) values (628, 'Famotidine - Acid Controller');
insert into DELIVERY_CMP (id, name) values (629, 'Duloxetine');
insert into DELIVERY_CMP (id, name) values (630, 'milk of magnesia');
insert into DELIVERY_CMP (id, name) values (631, 'ENALAPRIL MALEATE');
insert into DELIVERY_CMP (id, name) values (632, 'PAIN GOODBYE MEDICATED CREAM');
insert into DELIVERY_CMP (id, name) values (633, 'Clemastine Fumarate');
insert into DELIVERY_CMP (id, name) values (634, 'Unithroid');
insert into DELIVERY_CMP (id, name) values (635, 'zoledronic acid');
insert into DELIVERY_CMP (id, name) values (636, 'Degree');
insert into DELIVERY_CMP (id, name) values (637, 'Anti-Bacterial Hand');
insert into DELIVERY_CMP (id, name) values (638, 'Alprazolam');
insert into DELIVERY_CMP (id, name) values (639, 'Cell to Cell Essence 70mL');
insert into DELIVERY_CMP (id, name) values (640, 'ALREX');
insert into DELIVERY_CMP (id, name) values (641, 'Badger SPF 34 Anti-Bug Sunscreen');
insert into DELIVERY_CMP (id, name) values (642, 'Fluocinolone Acetonide');
insert into DELIVERY_CMP (id, name) values (643, 'Promolaxin');
insert into DELIVERY_CMP (id, name) values (644, 'Buprenorphine HCl and Naloxone HCl');
insert into DELIVERY_CMP (id, name) values (645, 'Amoxicillin');
insert into DELIVERY_CMP (id, name) values (646, 'Health Mart anti nausea');
insert into DELIVERY_CMP (id, name) values (647, 'Calcitriol');
insert into DELIVERY_CMP (id, name) values (648, 'Reguloid');
insert into DELIVERY_CMP (id, name) values (649, 'Morning Sickness Relief');
insert into DELIVERY_CMP (id, name) values (650, 'Diphenhydramine Hydrochloride');
insert into DELIVERY_CMP (id, name) values (651, 'Chlordiazepoxide Hydrochloride');
insert into DELIVERY_CMP (id, name) values (652, 'Softlips Intense Moisture Berry Mint');
insert into DELIVERY_CMP (id, name) values (653, 'SINGULAIR');
insert into DELIVERY_CMP (id, name) values (654, 'Ionite R');
insert into DELIVERY_CMP (id, name) values (655, 'nighttime sleep aid');
insert into DELIVERY_CMP (id, name) values (656, 'acarbose');
insert into DELIVERY_CMP (id, name) values (657, 'Cyclobenzaprine Hydrochloride');
insert into DELIVERY_CMP (id, name) values (658, 'String Beans');
insert into DELIVERY_CMP (id, name) values (659, 'Lamotrigine');
insert into DELIVERY_CMP (id, name) values (660, 'Dicyclomine Hydrochloride');
insert into DELIVERY_CMP (id, name) values (661, 'PANTOPRAZOLE SODIUM');
insert into DELIVERY_CMP (id, name) values (662, 'White Birch');
insert into DELIVERY_CMP (id, name) values (663, 'Thyro');
insert into DELIVERY_CMP (id, name) values (664, 'CLINIQUE');
insert into DELIVERY_CMP (id, name) values (665, 'Ondansetron');
insert into DELIVERY_CMP (id, name) values (666, 'Loratadine');
insert into DELIVERY_CMP (id, name) values (667, 'Sani Professional Brand Sani-Hands for KidsHand Wipes');
insert into DELIVERY_CMP (id, name) values (668, '7 select night time relief');
insert into DELIVERY_CMP (id, name) values (669, 'Infant Dextrose');
insert into DELIVERY_CMP (id, name) values (670, 'PINUS ECHINATA POLLEN');
insert into DELIVERY_CMP (id, name) values (671, 'GRx Dyne Scrub');
insert into DELIVERY_CMP (id, name) values (672, 'Amlodipine Besylate');
insert into DELIVERY_CMP (id, name) values (673, 'TYLENOL Extra Strength');
insert into DELIVERY_CMP (id, name) values (674, 'Stool Softener');
insert into DELIVERY_CMP (id, name) values (675, 'Atenolol and Chlorthalidone');
insert into DELIVERY_CMP (id, name) values (676, 'Neomycin and Polymyxin B Sulfates and Hydrocortisone');
insert into DELIVERY_CMP (id, name) values (677, 'AcetaZOLAMIDE');
insert into DELIVERY_CMP (id, name) values (678, 'Onfi');
insert into DELIVERY_CMP (id, name) values (679, 'Crestor');
insert into DELIVERY_CMP (id, name) values (680, 'Theophylline in Dextrose');
insert into DELIVERY_CMP (id, name) values (681, 'Theracodeine-300');
insert into DELIVERY_CMP (id, name) values (682, 'Cephalexin');
insert into DELIVERY_CMP (id, name) values (683, 'IOPE RETIGEN MOISTURE FOUNDATION');
insert into DELIVERY_CMP (id, name) values (684, 'Sei Bella Age-Defying Liquid Foundation');
insert into DELIVERY_CMP (id, name) values (685, 'TOPIRAMATE');
insert into DELIVERY_CMP (id, name) values (686, 'ACETAMINOPHEN AND DIPHENHYDRAMINE HYDROCHLORIDE');
insert into DELIVERY_CMP (id, name) values (687, 'SORGHUM HALEPENSE POLLEN');
insert into DELIVERY_CMP (id, name) values (688, 'Bupivacaine Hydrochloride and Epinephrine');
insert into DELIVERY_CMP (id, name) values (689, 'Guanfacine Hydrochloride');
insert into DELIVERY_CMP (id, name) values (690, 'daunorubicin hydrochloride');
insert into DELIVERY_CMP (id, name) values (691, 'Sunmark Acid Reducer');
insert into DELIVERY_CMP (id, name) values (692, 'Levofloxacin');
insert into DELIVERY_CMP (id, name) values (693, 'Advanced Protection');
insert into DELIVERY_CMP (id, name) values (694, '9-1-1 Stress Control');
insert into DELIVERY_CMP (id, name) values (695, 'Ondansetron hydrochloride and dextrose');
insert into DELIVERY_CMP (id, name) values (696, 'PredniSONE');
insert into DELIVERY_CMP (id, name) values (697, '');
insert into DELIVERY_CMP (id, name) values (698, 'PURELL Advanced E3 Rated Instant Hand Sanitizer');
insert into DELIVERY_CMP (id, name) values (699, 'CYZONE');
insert into DELIVERY_CMP (id, name) values (700, 'triamcinolone acetonide');
insert into DELIVERY_CMP (id, name) values (701, 'Spironolactone');
insert into DELIVERY_CMP (id, name) values (702, 'Calcipotriene');
insert into DELIVERY_CMP (id, name) values (703, 'CRYSELLE');
insert into DELIVERY_CMP (id, name) values (704, 'Peach');
insert into DELIVERY_CMP (id, name) values (705, 'Gold Bond Medicated Foot');
insert into DELIVERY_CMP (id, name) values (706, 'Cockroach American');
insert into DELIVERY_CMP (id, name) values (707, 'Levofloxacin');
insert into DELIVERY_CMP (id, name) values (708, 'Arnica Active');
insert into DELIVERY_CMP (id, name) values (709, 'ABILIFY');
insert into DELIVERY_CMP (id, name) values (710, 'Diazepam');
insert into DELIVERY_CMP (id, name) values (711, 'Norepinephrine bitartrate');
insert into DELIVERY_CMP (id, name) values (712, 'Diclofenac Potassium');
insert into DELIVERY_CMP (id, name) values (713, 'Lamotrigine');
insert into DELIVERY_CMP (id, name) values (714, 'Amerfresh Clear');
insert into DELIVERY_CMP (id, name) values (715, 'Dental plus Extra Menta');
insert into DELIVERY_CMP (id, name) values (716, 'Lice Complete');
insert into DELIVERY_CMP (id, name) values (717, 'Medline Alcohol Prep');
insert into DELIVERY_CMP (id, name) values (718, 'Australian Gold');
insert into DELIVERY_CMP (id, name) values (719, 'Doxepin Hydrochloride');
insert into DELIVERY_CMP (id, name) values (720, 'Dulera');
insert into DELIVERY_CMP (id, name) values (721, 'ZALEPLON');
insert into DELIVERY_CMP (id, name) values (722, 'Citrus Quartz');
insert into DELIVERY_CMP (id, name) values (723, 'Fever Reliever');
insert into DELIVERY_CMP (id, name) values (724, 'Flu Relief BP');
insert into DELIVERY_CMP (id, name) values (725, 'FERRUM PHOSPHATE');
insert into DELIVERY_CMP (id, name) values (726, 'Clindamycin');
insert into DELIVERY_CMP (id, name) values (727, 'Hydrocodone Bitartrate and Ibuprofen');
insert into DELIVERY_CMP (id, name) values (728, 'Valacyclovir Hydrochloride');
insert into DELIVERY_CMP (id, name) values (729, 'Nortriptyline Hydrochloride');
insert into DELIVERY_CMP (id, name) values (730, 'Meaningful Beauty Cindy Crawford Antioxidant');
insert into DELIVERY_CMP (id, name) values (731, 'SENSAI FLUID FINISH FF204');
insert into DELIVERY_CMP (id, name) values (732, 'nite time');
insert into DELIVERY_CMP (id, name) values (733, 'flormar REBORN FOUNDATION SUNSCREEN BROAD SPECTRUM SPF 20 SF13 Nude Ivory');
insert into DELIVERY_CMP (id, name) values (734, 'Carbidopa and Levodopa');
insert into DELIVERY_CMP (id, name) values (735, 'CANIS LUPUS FAMILIARIS SKIN');
insert into DELIVERY_CMP (id, name) values (736, 'Metoprolol Tartrate');
insert into DELIVERY_CMP (id, name) values (737, 'CD DiorSnow UV Protection BB Eye Sunscreen Creme 010');
insert into DELIVERY_CMP (id, name) values (738, 'Lysimachia Solanum 5');
insert into DELIVERY_CMP (id, name) values (739, 'CVS');
insert into DELIVERY_CMP (id, name) values (740, 'Olay Regenerist');
insert into DELIVERY_CMP (id, name) values (741, 'Heavy Metal - Amalga Detox');
insert into DELIVERY_CMP (id, name) values (742, 'Live Better');
insert into DELIVERY_CMP (id, name) values (743, 'Sunmark complete');
insert into DELIVERY_CMP (id, name) values (744, 'Wingscale');
insert into DELIVERY_CMP (id, name) values (745, 'No7 Beautiful Skin Oil Free Skin Protector All Skin Types SPF 25');
insert into DELIVERY_CMP (id, name) values (746, 'Zaleplon');
insert into DELIVERY_CMP (id, name) values (747, 'Carbon Dioxide Oxygen Mixture');
insert into DELIVERY_CMP (id, name) values (748, 'CLARINS Skin Illusion SPF 10 Natural Radiance Foundation Tint 113');
insert into DELIVERY_CMP (id, name) values (749, 'ABILIFY');
insert into DELIVERY_CMP (id, name) values (750, 'Cortizone 10 Cooling Cream Anti-Itch');
insert into DELIVERY_CMP (id, name) values (751, 'CENTER-AL - AMBROSIA ACANTHICARPA POLLEN');
insert into DELIVERY_CMP (id, name) values (752, 'Lenscale Quailbrush');
insert into DELIVERY_CMP (id, name) values (753, 'Bupropion Hydrochloride');
insert into DELIVERY_CMP (id, name) values (754, 'RED ORANGE SUN PACT');
insert into DELIVERY_CMP (id, name) values (755, 'Benzonatate');
insert into DELIVERY_CMP (id, name) values (756, 'Focalgin B');
insert into DELIVERY_CMP (id, name) values (757, 'BUPROPION HYDROCHLORIDE');
insert into DELIVERY_CMP (id, name) values (758, 'Vitamin A and D');
insert into DELIVERY_CMP (id, name) values (759, 'NEUPOGEN');
insert into DELIVERY_CMP (id, name) values (760, 'Loblolly Pine');
insert into DELIVERY_CMP (id, name) values (761, 'PYtest');
insert into DELIVERY_CMP (id, name) values (762, 'Rapamune');
insert into DELIVERY_CMP (id, name) values (763, 'Irbesartan and Hydrochlorothiazide');
insert into DELIVERY_CMP (id, name) values (764, 'Oxygen');
insert into DELIVERY_CMP (id, name) values (765, 'Ketoconazole');
insert into DELIVERY_CMP (id, name) values (766, 'Atomoxetine hydrochloride');
insert into DELIVERY_CMP (id, name) values (767, 'BUTALBITAL, ASPIRIN, AND CAFFEINE');
insert into DELIVERY_CMP (id, name) values (768, 'puristics baby zinc oxide diaper rash');
insert into DELIVERY_CMP (id, name) values (769, 'CARBOplatin');
insert into DELIVERY_CMP (id, name) values (770, 'Ibuprofen');
insert into DELIVERY_CMP (id, name) values (771, 'Metronidazole');
insert into DELIVERY_CMP (id, name) values (772, 'Gengraf');
insert into DELIVERY_CMP (id, name) values (773, 'A PERFECT WORLD');
insert into DELIVERY_CMP (id, name) values (774, 'Crest Anti-Cavity');
insert into DELIVERY_CMP (id, name) values (775, 'Finasteride');
insert into DELIVERY_CMP (id, name) values (776, 'Diflucan');
insert into DELIVERY_CMP (id, name) values (777, 'nifedipine');
insert into DELIVERY_CMP (id, name) values (778, 'Dicloxacillin Sodium');
insert into DELIVERY_CMP (id, name) values (779, 'Intelence');
insert into DELIVERY_CMP (id, name) values (780, 'Pioglitazone Hydrochloride');
insert into DELIVERY_CMP (id, name) values (781, 'Gas Relief');
insert into DELIVERY_CMP (id, name) values (782, 'Heparin Sodium');
insert into DELIVERY_CMP (id, name) values (783, 'RISPERIDONE');
insert into DELIVERY_CMP (id, name) values (784, 'Donatussin DROPS');
insert into DELIVERY_CMP (id, name) values (785, 'Advanced Relief A and D');
insert into DELIVERY_CMP (id, name) values (786, 'Warfarin Sodium');
insert into DELIVERY_CMP (id, name) values (787, 'CAREONE');
insert into DELIVERY_CMP (id, name) values (788, 'Bupropion Hydrochloride (SR)');
insert into DELIVERY_CMP (id, name) values (789, 'Childrens Pain Relief');
insert into DELIVERY_CMP (id, name) values (790, 'Salt Cedar');
insert into DELIVERY_CMP (id, name) values (791, 'Loperamide Hydrochloride');
insert into DELIVERY_CMP (id, name) values (792, 'Alprazolam');
insert into DELIVERY_CMP (id, name) values (793, 'VENTOLINHFA');
insert into DELIVERY_CMP (id, name) values (794, 'Atenolol and Chlorthalidone');
insert into DELIVERY_CMP (id, name) values (795, 'Cyclobenzaprine Hydrochloride');
insert into DELIVERY_CMP (id, name) values (796, 'LANDRUM INSTANT HAND SANITIZER');
insert into DELIVERY_CMP (id, name) values (797, 'Taurine');
insert into DELIVERY_CMP (id, name) values (798, 'Benadryl Extra Strength Itch Relief');
insert into DELIVERY_CMP (id, name) values (799, 'BareMinerals Dark Matte');
insert into DELIVERY_CMP (id, name) values (800, 'Methocarbamol');
insert into DELIVERY_CMP (id, name) values (801, 'Hydrocortisone');
insert into DELIVERY_CMP (id, name) values (802, 'Ursodiol');
insert into DELIVERY_CMP (id, name) values (803, 'Glyburide');
insert into DELIVERY_CMP (id, name) values (804, 'Ocudox');
insert into DELIVERY_CMP (id, name) values (805, 'Glucotrol XL');
insert into DELIVERY_CMP (id, name) values (806, 'Crest Anticavity Kit');
insert into DELIVERY_CMP (id, name) values (807, 'Grain and Seed Antigens');
insert into DELIVERY_CMP (id, name) values (808, 'Sun Protection Emulsion Face');
insert into DELIVERY_CMP (id, name) values (809, 'FLUZONE High-Dose');
insert into DELIVERY_CMP (id, name) values (810, 'Health Mart Pain Relief');
insert into DELIVERY_CMP (id, name) values (811, 'ciprofloxacin');
insert into DELIVERY_CMP (id, name) values (812, 'Tramadol Hydrochloride');
insert into DELIVERY_CMP (id, name) values (813, 'Ibuprofen');
insert into DELIVERY_CMP (id, name) values (814, 'Habitrol Patch');
insert into DELIVERY_CMP (id, name) values (815, 'Head and Shoulders Treatment');
insert into DELIVERY_CMP (id, name) values (816, 'Lipitor');
insert into DELIVERY_CMP (id, name) values (817, 'NORTRIPTYLINE HYDROCHLORIDE');
insert into DELIVERY_CMP (id, name) values (818, 'PRINIVIL');
insert into DELIVERY_CMP (id, name) values (819, 'Treatment Set TS347338');
insert into DELIVERY_CMP (id, name) values (820, 'Quetiapine Fumarate');
insert into DELIVERY_CMP (id, name) values (821, 'Fenofibrate');
insert into DELIVERY_CMP (id, name) values (822, 'Extreme GH');
insert into DELIVERY_CMP (id, name) values (823, 'ESIKA PERFECT SKIN COVERAGE CONCEALER SPF 17');
insert into DELIVERY_CMP (id, name) values (824, 'Oxygen');
insert into DELIVERY_CMP (id, name) values (825, 'PAROXETINE');
insert into DELIVERY_CMP (id, name) values (826, 'BD E-Z Scrub');
insert into DELIVERY_CMP (id, name) values (827, 'Losartan Potassium');
insert into DELIVERY_CMP (id, name) values (828, 'SierraSil');
insert into DELIVERY_CMP (id, name) values (829, 'Acid Reducer');
insert into DELIVERY_CMP (id, name) values (830, 'ELCURE CUREKIN');
insert into DELIVERY_CMP (id, name) values (831, 'BUDESONIDE');
insert into DELIVERY_CMP (id, name) values (832, 'lansoprazole');
insert into DELIVERY_CMP (id, name) values (833, 'Ondansetron');
insert into DELIVERY_CMP (id, name) values (834, 'CARBAMAZEPINE');
insert into DELIVERY_CMP (id, name) values (835, 'Witch Hazel');
insert into DELIVERY_CMP (id, name) values (836, 'anti-bacterial Hand Cleanser');
insert into DELIVERY_CMP (id, name) values (837, 'Bronchi HP');
insert into DELIVERY_CMP (id, name) values (838, 'cisatracurium besylate');
insert into DELIVERY_CMP (id, name) values (839, 'Homeopathic HCG Formula');
insert into DELIVERY_CMP (id, name) values (840, 'Origins');
insert into DELIVERY_CMP (id, name) values (841, 'Extra Strength Headache Relief');
insert into DELIVERY_CMP (id, name) values (842, 'Losartan Potassium');
insert into DELIVERY_CMP (id, name) values (843, 'East Sycamore');
insert into DELIVERY_CMP (id, name) values (844, 'Benztropine Mesylate');
insert into DELIVERY_CMP (id, name) values (845, 'Fiorinal with Codeine');
insert into DELIVERY_CMP (id, name) values (846, 'Ceramide Lift And Firm Makeup Broad Spectrum Sunscreen SPF 15 Warm Honey');
insert into DELIVERY_CMP (id, name) values (847, 'topcare nite time cold and flu relief');
insert into DELIVERY_CMP (id, name) values (848, 'Azathioprine');
insert into DELIVERY_CMP (id, name) values (849, 'Medicated');
insert into DELIVERY_CMP (id, name) values (850, 'Enalapril Maleate');
insert into DELIVERY_CMP (id, name) values (851, 'Multi Vitamin with Fluoride');
insert into DELIVERY_CMP (id, name) values (852, 'Oxybutynin Chloride');
insert into DELIVERY_CMP (id, name) values (853, 'Diabetic Siltussin DAS-Na');
insert into DELIVERY_CMP (id, name) values (854, 'TOPCO');
insert into DELIVERY_CMP (id, name) values (855, 'ZUSKA');
insert into DELIVERY_CMP (id, name) values (856, 'Thyro');
insert into DELIVERY_CMP (id, name) values (857, 'GUNA-FGF');
insert into DELIVERY_CMP (id, name) values (858, 'Zep Instant Hand Sanitizer');
insert into DELIVERY_CMP (id, name) values (859, 'PARASITE DETOX');
insert into DELIVERY_CMP (id, name) values (860, 'Ranitidine Hydrochloride');
insert into DELIVERY_CMP (id, name) values (861, 'Losartan Potassium');
insert into DELIVERY_CMP (id, name) values (862, 'Nite Time Cold and Flu');
insert into DELIVERY_CMP (id, name) values (863, 'Macadamia Nut');
insert into DELIVERY_CMP (id, name) values (864, 'CAREALL Bacitracin');
insert into DELIVERY_CMP (id, name) values (865, 'Carbon Dioxide-Oxygen-Nitrogen Mixture');
insert into DELIVERY_CMP (id, name) values (866, 'Ultravist');
insert into DELIVERY_CMP (id, name) values (867, 'Hand Sanitizer');
insert into DELIVERY_CMP (id, name) values (868, 'Longleaf Pine');
insert into DELIVERY_CMP (id, name) values (869, 'Glipizide');
insert into DELIVERY_CMP (id, name) values (870, 'ALOE SUN ESSENCE');
insert into DELIVERY_CMP (id, name) values (871, 'Hepar Stannum 6/10');
insert into DELIVERY_CMP (id, name) values (872, 'Daytime Cold and Pain Relief');
insert into DELIVERY_CMP (id, name) values (873, 'Butalbital, Acetaminophen and Caffeine with Codeine Phosphate');
insert into DELIVERY_CMP (id, name) values (874, 'Equaline Daytime Nighttime Cold and Flu Relief');
insert into DELIVERY_CMP (id, name) values (875, 'ESSENCE OF BEAUTY');
insert into DELIVERY_CMP (id, name) values (876, 'Lorazepam');
insert into DELIVERY_CMP (id, name) values (877, 'Fentanyl Citrate');
insert into DELIVERY_CMP (id, name) values (878, 'Childrens Non-Drowsy');
insert into DELIVERY_CMP (id, name) values (879, 'BioThrax');
insert into DELIVERY_CMP (id, name) values (880, 'Carvedilol');
insert into DELIVERY_CMP (id, name) values (881, 'Mucinex');
insert into DELIVERY_CMP (id, name) values (882, 'Olanzapine');
insert into DELIVERY_CMP (id, name) values (883, 'Ultracare Anesthetic');
insert into DELIVERY_CMP (id, name) values (884, 'COREGCR');
insert into DELIVERY_CMP (id, name) values (885, 'CombiPatch');
insert into DELIVERY_CMP (id, name) values (886, 'Glipizide');
insert into DELIVERY_CMP (id, name) values (887, 'PRAVASTATIN SODIUM');
insert into DELIVERY_CMP (id, name) values (888, 'Beyond Belief');
insert into DELIVERY_CMP (id, name) values (889, 'Sterile Water');
insert into DELIVERY_CMP (id, name) values (890, 'MEIJER ALOE GEL');
insert into DELIVERY_CMP (id, name) values (891, 'Oxycodone Hydrochloride');
insert into DELIVERY_CMP (id, name) values (892, 'Bupropion Hydrochloride');
insert into DELIVERY_CMP (id, name) values (893, 'SERTRALINE HYDROCHLORIDE');
insert into DELIVERY_CMP (id, name) values (894, 'PERIPLANETA AMERICANA');
insert into DELIVERY_CMP (id, name) values (895, 'Haloperidol');
insert into DELIVERY_CMP (id, name) values (896, 'Stool Softener');
insert into DELIVERY_CMP (id, name) values (897, 'Zoledronic Acid');
insert into DELIVERY_CMP (id, name) values (898, 'Sinus');
insert into DELIVERY_CMP (id, name) values (899, 'Fluide Fondant Desalterant SPF 15 Hydra Quench - Formula B');
insert into DELIVERY_CMP (id, name) values (900, 'Pollens - Weeds and Garden Plants, Dog Fennel, Eastern Eupatorium capillifolium');
insert into DELIVERY_CMP (id, name) values (901, 'Hydrocodone Bitartrate And Acetaminophen');
insert into DELIVERY_CMP (id, name) values (902, 'Oxybutynin Chloride');
insert into DELIVERY_CMP (id, name) values (903, 'Citalopram');
insert into DELIVERY_CMP (id, name) values (904, 'Azithromycin');
insert into DELIVERY_CMP (id, name) values (905, 'Nicotine polacrilex');
insert into DELIVERY_CMP (id, name) values (906, 'Fresh Umbrian Clay Freshface Foundation SPF 20 Chalet Girl');
insert into DELIVERY_CMP (id, name) values (907, 'Hydromorphone HCl');
insert into DELIVERY_CMP (id, name) values (908, 'Amoxicillin');
insert into DELIVERY_CMP (id, name) values (909, 'ACER SACCHARUM POLLEN');
insert into DELIVERY_CMP (id, name) values (910, 'Tenzer');
insert into DELIVERY_CMP (id, name) values (911, 'Rifadin IV');
insert into DELIVERY_CMP (id, name) values (912, 'Acne Body Wash');
insert into DELIVERY_CMP (id, name) values (913, 'Amoxicillin and Clavulanate Potassium');
insert into DELIVERY_CMP (id, name) values (914, 'Pac-Dent Top Gel');
insert into DELIVERY_CMP (id, name) values (915, 'Triamcinolone Acetonide');
insert into DELIVERY_CMP (id, name) values (916, 'hydrocortisone Iodoquinol');
insert into DELIVERY_CMP (id, name) values (917, 'MEIJER');
insert into DELIVERY_CMP (id, name) values (918, 'VALPROIC ACID');
insert into DELIVERY_CMP (id, name) values (919, 'Pollens - Weeds and Garden Plants, Lambs Quarters Chenopodium album');
insert into DELIVERY_CMP (id, name) values (920, 'Anticavity Fluoride Rinse');
insert into DELIVERY_CMP (id, name) values (921, 'Levofloxacin');
insert into DELIVERY_CMP (id, name) values (922, 'METFORMIN HYDROCHLORIDE');
insert into DELIVERY_CMP (id, name) values (923, 'Alprazolam');
insert into DELIVERY_CMP (id, name) values (924, 'Emesyl Nausea Relief');
insert into DELIVERY_CMP (id, name) values (925, 'Intralipid');
insert into DELIVERY_CMP (id, name) values (926, 'DEMEROL');
insert into DELIVERY_CMP (id, name) values (927, 'DULOXETINE');
insert into DELIVERY_CMP (id, name) values (928, 'PURE SHEER');
insert into DELIVERY_CMP (id, name) values (929, 'Aveed');
insert into DELIVERY_CMP (id, name) values (930, 'UltrasolSunscreen');
insert into DELIVERY_CMP (id, name) values (931, 'Morphine Sulfate');
insert into DELIVERY_CMP (id, name) values (932, 'ZEA MAYS POLLEN');
insert into DELIVERY_CMP (id, name) values (933, 'Anti-Bacterial Hand');
insert into DELIVERY_CMP (id, name) values (934, 'Gehwol med Lipidro');
insert into DELIVERY_CMP (id, name) values (935, 'UROGESIC BLUE');
insert into DELIVERY_CMP (id, name) values (936, 'Oxygen');
insert into DELIVERY_CMP (id, name) values (937, 'RHODOTORULA MUCILAGINOSA');
insert into DELIVERY_CMP (id, name) values (938, 'Glipizide');
insert into DELIVERY_CMP (id, name) values (939, 'Protector SPF 15');
insert into DELIVERY_CMP (id, name) values (940, 'School Health Sterile Alcohol Prep Pad');
insert into DELIVERY_CMP (id, name) values (941, 'Phenylephrine Hydrochloride');
insert into DELIVERY_CMP (id, name) values (942, 'Garnier UltraLift Transformer AntiAge Skin Corrector Broad Spectrum SPF 20 Sunscreen');
insert into DELIVERY_CMP (id, name) values (943, 'SENSORCAINE');
insert into DELIVERY_CMP (id, name) values (944, 'Stool Softener and Stimulant Laxative');
insert into DELIVERY_CMP (id, name) values (945, 'PHS Hair Science Hom Hair Loss Tonic');
insert into DELIVERY_CMP (id, name) values (946, 'Bedwetting');
insert into DELIVERY_CMP (id, name) values (947, 'Oxygen');
insert into DELIVERY_CMP (id, name) values (948, 'Lisinopril and hydrochlorothiazide');
insert into DELIVERY_CMP (id, name) values (949, 'TopCare Allergy Relief D');
insert into DELIVERY_CMP (id, name) values (950, 'Temazepam');
insert into DELIVERY_CMP (id, name) values (951, 'DIAZEPAM');
insert into DELIVERY_CMP (id, name) values (952, 'Superdent');
insert into DELIVERY_CMP (id, name) values (953, 'Quinapril');
insert into DELIVERY_CMP (id, name) values (954, 'Up and Up Cough Suppressant DM');
insert into DELIVERY_CMP (id, name) values (955, 'Misoprostol');
insert into DELIVERY_CMP (id, name) values (956, 'Miconazole 1');
insert into DELIVERY_CMP (id, name) values (957, 'UltraMax Invisible Solid');
insert into DELIVERY_CMP (id, name) values (958, 'Arniflora');
insert into DELIVERY_CMP (id, name) values (959, 'Manderin Orange Antibacterial Foaming Hand Wash');
insert into DELIVERY_CMP (id, name) values (960, 'Russian Thistle');
insert into DELIVERY_CMP (id, name) values (961, 'HELIOX');
insert into DELIVERY_CMP (id, name) values (962, 'BLEMISH LAB BYE PORE BB');
insert into DELIVERY_CMP (id, name) values (963, 'Axe');
insert into DELIVERY_CMP (id, name) values (964, 'albuterol sulfate');
insert into DELIVERY_CMP (id, name) values (965, 'Levofloxacin');
insert into DELIVERY_CMP (id, name) values (966, 'DG Health Cold Head Congestion');
insert into DELIVERY_CMP (id, name) values (967, 'eye itch relief');
insert into DELIVERY_CMP (id, name) values (968, 'losartan potassium');
insert into DELIVERY_CMP (id, name) values (969, 'Naproxen');
insert into DELIVERY_CMP (id, name) values (970, 'enema');
insert into DELIVERY_CMP (id, name) values (971, 'Gabapentin');
insert into DELIVERY_CMP (id, name) values (972, 'Berkley and Jensen Omeprazole');
insert into DELIVERY_CMP (id, name) values (973, 'Fentanyl Citrate');
insert into DELIVERY_CMP (id, name) values (974, 'LEVOTHYROXINE SODIUM');
insert into DELIVERY_CMP (id, name) values (975, 'NITROGEN');
insert into DELIVERY_CMP (id, name) values (976, 'Terbutaline Sulfate');
insert into DELIVERY_CMP (id, name) values (977, 'iBaba');
insert into DELIVERY_CMP (id, name) values (978, 'Silky Finish');
insert into DELIVERY_CMP (id, name) values (979, 'MAX HYALURONIC STEMCELL BB');
insert into DELIVERY_CMP (id, name) values (980, 'Chemstar InstantFOAM NonAlcohol Sanitizer');
insert into DELIVERY_CMP (id, name) values (981, 'POA ANNUA POLLEN');
insert into DELIVERY_CMP (id, name) values (982, 'LBEL');
insert into DELIVERY_CMP (id, name) values (983, 'Hydrocodone Bitartrate And Acetaminophen');
insert into DELIVERY_CMP (id, name) values (984, 'Ulesfia');
insert into DELIVERY_CMP (id, name) values (985, 'Morphine Sulfate');
insert into DELIVERY_CMP (id, name) values (986, 'Risperidone');
insert into DELIVERY_CMP (id, name) values (987, 'Estradiol / Norethindrone Acetate');
insert into DELIVERY_CMP (id, name) values (988, 'Sumaxin');
insert into DELIVERY_CMP (id, name) values (989, 'Haloperidol');
insert into DELIVERY_CMP (id, name) values (990, 'MUCOSA');
insert into DELIVERY_CMP (id, name) values (991, 'MAXALT');
insert into DELIVERY_CMP (id, name) values (992, 'Ibuprofen');
insert into DELIVERY_CMP (id, name) values (993, 'nifedipine');
insert into DELIVERY_CMP (id, name) values (994, 'Bacitracin Zinc');
insert into DELIVERY_CMP (id, name) values (995, 'Tussin Original');
insert into DELIVERY_CMP (id, name) values (996, 'daytime pe nitetime');
insert into DELIVERY_CMP (id, name) values (997, 'Refuge HC');
insert into DELIVERY_CMP (id, name) values (998, 'BPO 3 Foaming');
insert into DELIVERY_CMP (id, name) values (999, 'Penicilium chrysogenum');
insert into DELIVERY_CMP (id, name) values (1000, 'Lisinopril and Hydrochlorothiazide');
